module

public import Contract.Euporia

/-! Proofs of the theorems the /elicit SKILL.md Lean block states; `Contract.Euporia` is that block,
    generated by lean-contract.js. -/

public section

open Ground

namespace Euporia

variable {P : Type}

theorem acceptedAux_skip (x : Coordinate) (pre ts : Context P) (acc : Option Value)
    (h : ∀ t ∈ ts, t.basis ≠ some .utterance) :
    acceptedAux x pre ts acc = acc := by
  induction ts generalizing pre acc with
  | nil => rfl
  | cons t ts ih =>
    have hn : ¬ (t.basis = some .utterance) := h t (by simp)
    simp only [acceptedAux, hn, ↓reduceIte]
    exact ih _ _ (fun t' ht' => h t' (by simp [ht']))

theorem acceptedAux_append (x : Coordinate) (pre c e : Context P) (acc : Option Value) :
    acceptedAux x pre (c ++ e) acc = acceptedAux x (pre ++ c) e (acceptedAux x pre c acc) := by
  induction c generalizing pre acc with
  | nil => simp [acceptedAux]
  | cons t ts ih =>
    simp only [List.cons_append, acceptedAux]
    rw [ih]
    simp

theorem accepted_revised_only_by_utterance (c e : Context P) (x : Coordinate)
    (h : ∀ t ∈ e, t.basis ≠ some .utterance) : accepted (c ++ e) x = accepted c x := by
  simp only [accepted]
  rw [acceptedAux_append]
  exact acceptedAux_skip x _ e _ h

theorem silence (respond : Context P → Response P) (c : Context P) :
    elicit respond c [] = .holding c := rfl

theorem resolved_here (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : answer (fuse c u) = .resolved) :
    elicit respond c (u :: us) = .resolved (endpoint (fuse c u) false) := by
  simp [elicit, h]

theorem parked_in_residual (c : Context P) (d : Bool) (x : Coordinate) (hx : x ∈ parked c) :
    ResidualItem.coordinate x ∈ residualAt c d := by
  simp only [residualAt, List.mem_append, List.mem_map]
  exact .inl (.inr ⟨x, hx, rfl⟩)

theorem endpoint_ends_in_utterance (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : ResolvedEndpoint P) (h : elicit respond c us = .resolved r) :
    ∃ (c₀ : Context P) (u : Utterance P), r.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    simp only [elicit] at h
    split at h
    · cases h; exact ⟨c, u, rfl⟩
    · cases h; exact ⟨c, u, rfl⟩
    · exact ih _ h

end Euporia
