module

public import Contract.Euporia

/-! The theorems the /elicit contract guarantees, each stated and proved here; `Contract.Euporia` is
    the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee the
    audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Euporia

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    elicit respond c [] = .holding c := by
  simp [elicit]

theorem nothing_to_elicit_surfaces_nothing (report respond : Context P → Response P)
    (c : Context P) (us : List (Utterance P)) (h : ¬ aporia c) :
    start report respond c us = .nothingToElicit (c ++ [(report c).val]) := by
  simp [start, h]

theorem unrelated_adds_no_gate (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : ¬ Reaches (fuse c u)) :
    elicit respond c (u :: us) = elicit respond (fuse c u) us := by
  simp [elicit, h]

theorem withdraw_closes_unresolved (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hr : Reaches (fuse c u))
    (h : isFilled (withdrawal (fuse c u)) = true) :
    elicit respond c (u :: us) = .withdrawn (closed (fuse c u)) := by
  simp [elicit, hr, h]

theorem covered_resolution_needs_no_further_utterance (respond : Context P → Response P)
    (c : Context P) (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false) (hr : isFilled (resolution (fuse c u)) = true)
    (hc : Covered (fuse c u)) :
    elicit respond c (u :: us) = .resolved (endpoint (fuse c u)) := by
  simp [elicit, hre, hw, hr, hc]

theorem uncovered_surfaces_again (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false) (hc : ¬ Covered (fuse c u)) :
    elicit respond c (u :: us) =
      elicit respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [elicit, hre, hw, hc]

theorem each_step_continues_or_closes (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (o : Outcome P)
    (h : elicit respond c (u :: us) = o) :
    (∃ c', elicit respond c' us = o) ∨
    (isFilled (withdrawal (fuse c u)) = true ∧ o = .withdrawn (closed (fuse c u))) ∨
    (isFilled (resolution (fuse c u)) = true ∧ Covered (fuse c u) ∧
      o = .resolved (endpoint (fuse c u))) := by
  simp only [elicit] at h
  split at h
  · exact .inl ⟨_, h⟩
  · split at h
    · exact .inr (.inl ⟨by assumption, h.symm⟩)
    · split at h
      · rename_i hrc
        exact .inr (.inr ⟨hrc.1, hrc.2, h.symm⟩)
      · exact .inl ⟨_, h⟩

theorem resolved_requires_covered (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : ResolvedEndpoint P)
    (h : elicit respond c us = .resolved r) :
    ∃ c₀, isFilled (resolution c₀) = true ∧ Covered c₀ ∧ r = endpoint c₀ := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨hr, hc, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨_, hr, hc, rfl⟩

theorem endpoint_ends_in_utterance (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : ResolvedEndpoint P)
    (h : elicit respond c us = .resolved r) :
    ∃ (c₀ : Context P) (u : Utterance P), r.closure.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨_, _, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨c, u, rfl⟩

theorem withdrawn_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Closed P) (h : elicit respond c us = .withdrawn r) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀ := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨hw, h'⟩ | ⟨_, _, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, hw, rfl⟩
    · cases h'

private theorem mem_recordOf {c : Context P} {x : Entry} {o : Occ (standingCoord (P := P) x) c}
    {r : Recorded c} (h : r ∈ recordOf x o) : r.coord = x ∧ isFilled o = true := by
  cases o with
  | open_ _ => simp [recordOf] at h
  | filled d s allowed supported =>
    simp only [recordOf, List.mem_singleton] at h
    subst h
    exact ⟨rfl, rfl⟩

theorem recorded_by_person (c : Context P) (r : Recorded c) (_ : r ∈ record c) :
    r.src.src.val = .person ∧ StandingSupported r.coord c (c[r.src.idx]'r.src.lt) r.det :=
  ⟨r.byPerson, r.supported⟩

theorem recorded_is_filled (c : Context P) (r : Recorded c) (h : r ∈ record c) :
    r.coord ∈ coordinates c ∧ isFilled (operative c r.coord) = true := by
  simp only [record, List.mem_flatMap] at h
  obtain ⟨x, hx, hr⟩ := h
  obtain ⟨hc, hf⟩ := mem_recordOf hr
  subst hc
  exact ⟨hx, hf⟩

theorem open_not_recorded (c : Context P) (x : Entry) (ho : isFilled (operative c x) = false)
    (r : Recorded c) (h : r ∈ record c) : r.coord ≠ x := by
  intro hx
  have := (recorded_is_filled c r h).2
  rw [hx, ho] at this
  cases this

theorem open_in_residual (c : Context P) (x : Entry) (hx : x ∈ coordinates c)
    (ho : isFilled (operative c x) = false) : x ∈ residual c := by
  simp [residual, hx, ho]

theorem stands_only_by_person {c : Context P} {x : Entry} {s : Cite c}
    (ok : (standingCoord (P := P) x).admits s.src) : s.src.val = .person := ok

theorem resolved_by_person {c : Context P} {s : Cite c}
    (ok : (resolutionCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem withdrawn_only_by_person {c : Context P} {s : Cite c}
    (ok : (withdrawalCoord (P := P)).admits s.src) : s.src.val = .person := ok

end Euporia
