module

public import Contract.Euporia

/-! The theorems the /elicit contract guarantees, each stated and proved here; `Contract.Euporia` is
    the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee the
    audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Euporia

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    elicit respond c [] = .holding c := by
  simp [elicit]

theorem nothing_to_elicit_surfaces_nothing (report respond : Context P → Response P)
    (c : Context P) (us : List (Utterance P)) (h : ¬ aporia c) :
    start report respond c us = .nothingToElicit (c ++ [(report c).val]) := by
  simp [start, h]

theorem withdraw_closes_unresolved (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P))
    (h : isFilled (withdrawal (fuse c u)) = true) :
    elicit respond c (u :: us) = .withdrawn (closed (fuse c u)) := by
  simp [elicit, h]

theorem covered_resolution_needs_no_further_utterance (respond : Context P → Response P)
    (c : Context P) (u : Utterance P) (us : List (Utterance P))
    (hw : isFilled (withdrawal (fuse c u)) = false) (hr : isFilled (resolution (fuse c u)) = true)
    (hc : Covered (fuse c u)) :
    elicit respond c (u :: us) = .resolved (endpoint (fuse c u)) := by
  simp [elicit, hw, hr, hc]

theorem uncovered_surfaces_again (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P))
    (hw : isFilled (withdrawal (fuse c u)) = false) (hc : ¬ Covered (fuse c u)) :
    elicit respond c (u :: us) =
      elicit respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [elicit, hw, hc]

theorem each_step_continues_or_closes (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (o : Outcome P)
    (h : elicit respond c (u :: us) = o) :
    (∃ c', elicit respond c' us = o) ∨
    (isFilled (withdrawal (fuse c u)) = true ∧ o = .withdrawn (closed (fuse c u))) ∨
    (isFilled (resolution (fuse c u)) = true ∧ Covered (fuse c u) ∧
      o = .resolved (endpoint (fuse c u))) := by
  simp only [elicit] at h
  split at h
  · exact .inr (.inl ⟨by assumption, h.symm⟩)
  · split at h
    · rename_i hrc
      exact .inr (.inr ⟨hrc.1, hrc.2, h.symm⟩)
    · exact .inl ⟨_, h⟩

theorem resolved_requires_covered (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : ResolvedEndpoint P)
    (h : elicit respond c us = .resolved r) :
    ∃ c₀, isFilled (resolution c₀) = true ∧ Covered c₀ ∧ r = endpoint c₀ := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨hr, hc, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨_, hr, hc, rfl⟩

theorem endpoint_ends_in_utterance (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : ResolvedEndpoint P)
    (h : elicit respond c us = .resolved r) :
    ∃ (c₀ : Context P) (u : Utterance P), r.record.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨_, _, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨c, u, rfl⟩

theorem withdrawn_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Closed P) (h : elicit respond c us = .withdrawn r) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀ := by
  induction us generalizing c with
  | nil => simp [elicit] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond c u us _ h with
        ⟨c', h'⟩ | ⟨hw, h'⟩ | ⟨_, _, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, hw, rfl⟩
    · cases h'

theorem proposed_never_set (c : Context P) (e : Entry) (h : proposer c e = .draft) :
    standing c e ≠ .set := by
  unfold standing
  cases withinGrant c e <;> simp [h]

theorem granted_stands_as_granted (c : Context P) (e : Entry) (h : withinGrant c e = true) :
    standing c e = .granted := by
  simp [standing, h]

theorem open_in_residual (c : Context P) (x : Entry) (hx : x ∈ coordinates c)
    (ho : isFilled (operative c x) = false) : x ∈ residual c := by
  simp [residual, hx, ho]

theorem resolved_by_person {c : Context P} {s : Cite c}
    (ok : (resolutionCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem withdrawn_only_by_person {c : Context P} {s : Cite c}
    (ok : (withdrawalCoord (P := P)).admits s.src) : s.src.val = .person := ok

end Euporia
