module

public import Contract.Hyphegesis

/-! Proofs of the theorems the /conduct SKILL.md Lean block states; `Contract.Hyphegesis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Hyphegesis

variable {P : Type}

theorem silence (respond : Context P → Response P) (c : Context P) :
    conduct respond c [] = .holding c := by
  simp [conduct]

theorem conducted_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (m : ConductedMethod P)
    (h : conduct respond c us = .conducted m) :
    ∃ (c₀ : Context P) (u : Utterance P), stage (fuse c₀ u) = .design ∧
      verdict (fuse c₀ u) = .sufficient ∧ ¬ Unshown (fuse c₀ u) ∧ m = method (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    simp only [conduct] at h
    split at h
    · split at h
      · cases h
      · exact ih _ h
    · exact ih _ h
    · cases h
    · rename_i hs
      split at h
      · rename_i hv
        cases h
        exact ⟨c, u, hs, hv.1, hv.2, rfl⟩
      · exact ih _ h

theorem exit_only_shown (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (hs : stage (fuse c u) = .design) (hn : Unshown (fuse c u)) :
    conduct respond c (u :: us) = conduct respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [conduct, hs, hn]

theorem person_value_taken (c : Context P) (s : Slot) (v : SlotVal s)
    (h : filledValue (slot c s) = some v) : (method c).topology s = v := by
  simp [method, take, h]

theorem emergent_stop_never_silent (e : Emergent)
    (h : ObligationClass.needsStopGround ∈ e.classes) :
    (groundOf (.emergent e)).isSome = true := by
  simp [groundOf, Option.isSome_map, e.owed h]

theorem pointer_carried (c : Context P) : (method c).pointer = pointer c := rfl

theorem accepted_by_utterance {c : Context P} {s : Cite c}
    (ok : (briefCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem moves_by_utterance {c : Context P} {s : Cite c}
    (ok : (moveSetCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem slot_by_utterance {c : Context P} {x : Slot} {s : Cite c}
    (ok : (slotCoord (P := P) x).admits s.kind) : s.kind = .utterance := ok

theorem feasibility_by_observation {c : Context P} {r : Region} {s : Cite c}
    (ok : (feasibilityCoord (P := P) r).admits s.kind) : s.kind = .observation := ok

theorem injected_grounds_nothing (e : Turn P) (h : e.origin = .injected) : e.basis = none := by
  cases e with
  | mk o f x =>
    simp only at h
    subst h
    cases f <;> rfl

end Hyphegesis
