module

public import Contract.Hyphegesis

/-! Proofs of the theorems the /conduct SKILL.md Lean block states; `Contract.Hyphegesis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Hyphegesis

variable {P : Type}

theorem silence (respond : Context P → Response P) (c : Context P) :
    conduct respond c [] = .holding c := by
  simp [conduct]

theorem conducted_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (t : Response P)
    (h : conduct respond c us = .conducted c₁ t) :
    ∃ (c₀ : Context P) (u : Utterance P), c₁ = observe (fuse c₀ u) ∧
      verdict c₁ = .sufficient ∧ Covered c₁ ∧ IsPartition (moves c₁) (cut c₁) ∧
      relayAt c₁ = none ∧ t = respond c₁ := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    simp only [conduct] at h
    split at h
    · cases h
    · cases h
    · rename_i v hw hr
      split at h
      · cases h
      · rename_i hrel
        split at h
        · rename_i hc
          cases h
          exact ⟨c, u, rfl, hc.1, hc.2.1, hc.2.2, hrel, rfl⟩
        · exact ih _ h

theorem withdrawn_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (h : conduct respond c us = .withdrawn c₁) :
    ∃ (c₀ : Context P) (u : Utterance P), c₁ = observe (fuse c₀ u) ∧ verdict c₁ = .withdraw := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    simp only [conduct] at h
    split at h
    · rename_i hv
      cases h
      exact ⟨c, u, rfl, hv⟩
    · cases h
    · split at h
      · cases h
      · split at h
        · cases h
        · exact ih _ h

theorem routed_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (t : String) (c₁ : Context P)
    (h : conduct respond c us = .routed t c₁) :
    ∃ (c₀ : Context P) (u : Utterance P), c₁ = observe (fuse c₀ u) ∧ verdict c₁ = .route t := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    simp only [conduct] at h
    split at h
    · cases h
    · rename_i t' hv
      cases h
      exact ⟨c, u, rfl, hv⟩
    · split at h
      · cases h
      · split at h
        · cases h
        · exact ih _ h

theorem withdraw_precedes_relay (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : verdict (observe (fuse c u)) = .withdraw) :
    conduct respond c (u :: us) = .withdrawn (observe (fuse c u)) := by
  simp [conduct, h]

theorem uncovered_redraws (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (hs : verdict (observe (fuse c u)) = .sufficient)
    (hr : relayAt (observe (fuse c u)) = none) (hn : ¬ Covered (observe (fuse c u))) :
    conduct respond c (u :: us) =
      conduct respond (observe (fuse c u) ++ [(respond (observe (fuse c u))).val]) us := by
  simp [conduct, hs, hr, hn]

theorem person_value_taken (c : Context P) (s : Slot) (v : SlotVal s)
    (h : filledValue (slot c s) = some v) : (method c).topology s = v := by
  simp [method, take, h]

theorem person_value_recorded (c : Context P) (s : Slot) (h : isFilled (slot c s) = true) :
    adoption c s = .set := by
  simp [adoption, h]

theorem every_move_placed (c : Context P) (h : IsPartition (moves c) (cut c)) :
    ∀ p ∈ (method c).assignment, p.region.isSome = true := by
  intro p hp
  simp only [method, assignment, List.mem_map] at hp
  obtain ⟨m, hm, rfl⟩ := hp
  obtain ⟨r, hr, hmr⟩ := h.1 m hm
  simp only [regionOf, List.find?_isSome]
  exact ⟨r, hr, List.elem_iff.mpr hmr⟩

theorem ungrounded_is_default (c : Context P) (s : Slot) (hs : isFilled (slot c s) = false)
    (hg : (draft c s).ground = none) : take c s = defaultValue s := by
  unfold take
  cases h : slot c s with
  | open_ _ => exact (draft c s).fallback hg
  | filled a src allowed supported => rw [h] at hs; simp [isFilled] at hs

theorem emergent_stop_never_silent (e : Emergent)
    (h : ObligationClass.needsStopGround ∈ e.classes) :
    (groundOf (.emergent e)).isSome = true := by
  simp [groundOf, Option.isSome_map, e.owed h]

theorem pointer_carried (c : Context P) : (method c).pointer = pointer c := rfl

theorem moves_by_utterance {c : Context P} {s : Cite c}
    (ok : (moveSetCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem cut_by_utterance {c : Context P} {s : Cite c}
    (ok : (cutCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem slot_by_utterance {c : Context P} {x : Slot} {s : Cite c}
    (ok : (slotCoord (P := P) x).admits s.kind) : s.kind = .utterance := ok

theorem feasibility_by_observation {c : Context P} {r : Region} {s : Cite c}
    (ok : (feasibilityCoord (P := P) r).admits s.kind) : s.kind = .observation := ok

theorem injected_grounds_nothing (e : Turn P) (h : e.origin = .injected) : e.basis = none := by
  cases e with
  | mk o f x =>
    simp only at h
    subst h
    cases f <;> rfl

end Hyphegesis
