module

public import Contract.Hyphegesis

/-! The theorems the /conduct contract guarantees, each stated and proved here;
    `Contract.Hyphegesis` is the SKILL.md Lean block, generated by lean-contract.js. Every public
    theorem is a guarantee the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Hyphegesis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond session : Context P → Response P) (c : Context P) :
    conduct respond session c [] = .holding c := by
  simp [conduct]

theorem start_opens_on_map (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (h : isFilled (relay (observe c)) = false) :
    start respond session c us =
      conduct respond session (observe c ++ [(respond (observe c)).val]) us := by
  simp [start, h]

theorem unrelated_holds_gate (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : ¬ Reaches (fuse c u)) :
    conduct respond session c (u :: us) =
      conduct respond session (fuse c u ++ [(session (fuse c u)).val]) us := by
  simp [conduct, h]

theorem untaken_redraws (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false)
    (hr : isFilled (resolution (observe (fuse c u))) = false) :
    conduct respond session c (u :: us) =
      conduct respond session
        (observe (fuse c u) ++ [(respond (observe (fuse c u))).val]) us := by
  simp [conduct, hre, hw, hr]

theorem taking_hands_off_without_redraw (respond session : Context P → Response P)
    (c : Context P) (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false)
    (hr : isFilled (resolution (observe (fuse c u))) = true) :
    conduct respond session c (u :: us) =
      .conducted (observe (fuse c u)) (respond (observe (fuse c u))) := by
  simp [conduct, hre, hw, hr]

theorem observe_extends (c : Context P) : c <+: observe c := by
  simp only [observe]
  exact (List.prefix_append _ _).trans (List.prefix_append _ _)

theorem each_step_continues_or_closes (respond session : Context P → Response P)
    (c : Context P) (u : Utterance P) (us : List (Utterance P)) (o : Outcome P)
    (h : conduct respond session c (u :: us) = o) :
    (∃ c', c <+: c' ∧ conduct respond session c' us = o) ∨
    (isFilled (withdrawal (fuse c u)) = true ∧
      o = .withdrawn (closed (fuse c u))) ∨
    (isFilled (resolution (observe (fuse c u))) = true ∧
      o = .conducted (observe (fuse c u)) (respond (observe (fuse c u)))) := by
  have fused : ∀ t : List (Turn P), c <+: fuse c u ++ t := fun t =>
    (List.prefix_append c [u.val]).trans (List.prefix_append _ _)
  have grows : ∀ t : List (Turn P), c <+: observe (fuse c u) ++ t := fun t =>
    ((List.prefix_append c [u.val]).trans (observe_extends _)).trans (List.prefix_append _ _)
  simp only [conduct] at h
  split at h
  · exact .inl ⟨_, fused _, h⟩
  · split at h
    · exact .inr (.inl ⟨by assumption, h.symm⟩)
    · split at h
      · rename_i hr
        exact .inr (.inr ⟨hr, h.symm⟩)
      · exact .inl ⟨_, grows _, h⟩

theorem conducted_by_person (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (t : Response P)
    (h : conduct respond session c us = .conducted c₁ t) :
    c <+: c₁ ∧ isFilled (resolution c₁) = true ∧ t = respond c₁ := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', hp, h'⟩ | ⟨_, h'⟩ | ⟨hr, h'⟩
    · have := ih c' h'
      exact ⟨hp.trans this.1, this.2⟩
    · cases h'
    · cases h'
      exact ⟨(List.prefix_append c [u.val]).trans (observe_extends _), hr, rfl⟩

theorem map_shown_never_relays (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (t : Response P) :
    conduct respond session c us ≠ .relayed c₁ t := by
  intro h
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', -, h'⟩ | ⟨_, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'

theorem withdrawn_by_person (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Closed P)
    (h : conduct respond session c us = .withdrawn r) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀ := by
  induction us generalizing c with
  | nil => simp [conduct] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', -, h'⟩ | ⟨hw, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, hw, rfl⟩
    · cases h'

theorem start_closes_only_by_person (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) :
    (∀ c₁ t, start respond session c us = .conducted c₁ t →
      c <+: c₁ ∧ isFilled (resolution c₁) = true) ∧
    (∀ c₁ t, start respond session c us = .relayed c₁ t →
      c₁ = observe c ∧ isFilled (relay c₁) = true) ∧
    (∀ r, start respond session c us = .withdrawn r →
      ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀) := by
  refine ⟨?_, ?_, ?_⟩
  · intro c₁ t h
    simp only [start] at h
    split at h
    · cases h
    · have := conducted_by_person respond session _ us c₁ t h
      exact ⟨((observe_extends c).trans (List.prefix_append _ _)).trans this.1, this.2.1⟩
  · intro c₁ t h
    simp only [start] at h
    split at h
    · rename_i hr
      cases h
      exact ⟨rfl, hr⟩
    · exact absurd h (map_shown_never_relays respond session _ us c₁ t)
  · intro r h
    simp only [start] at h
    split at h
    · cases h
    · exact withdrawn_by_person respond session _ us r h

theorem withdrawal_and_holding_hand_off_nothing (r : Closed P) (c : Context P) :
    handedOffBy (.withdrawn r) = none ∧ handedOffBy (.holding c : Outcome P) = none :=
  ⟨rfl, rfl⟩

theorem closure_hands_off (c : Context P) (t : Response P) :
    handedOffBy (.conducted c t) = some .handoff ∧ handedOffBy (.relayed c t) = some .handoff :=
  ⟨rfl, rfl⟩

theorem handoff_only_by_person (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (h : handedOffBy (start respond session c us) = some .handoff) :
    (∃ c₁ : Context P, c <+: c₁ ∧ isFilled (resolution c₁) = true) ∨
      isFilled (relay (observe c)) = true := by
  have ⟨hc, hr, _⟩ := start_closes_only_by_person respond session c us
  cases ho : start respond session c us with
  | conducted c₁ t => exact .inl ⟨c₁, hc c₁ t ho⟩
  | relayed c₁ t =>
    have ⟨e, f⟩ := hr c₁ t ho
    exact .inr (e ▸ f)
  | withdrawn r => rw [ho] at h; simp [handedOffBy] at h
  | holding c₁ => rw [ho] at h; simp [handedOffBy] at h

theorem handoff_carries_obligations (c : Context P) :
    (emitted c).plan = draft c ∧ (emitted c).record = record c ∧
      (emitted c).residual = residual c ∧ (emitted c).deferred = deferred c ∧
      (emitted c).required = required c ∧ (emitted c).feasibility = feasibility c ∧
      (emitted c).lifetime = lifetime c ∧ (emitted c).placement = placement c ∧
      (emitted c).pointer = pointer c ∧ (emitted c).source = source c ∧
      (emitted c).dissent = dissent c :=
  ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

theorem withdrawal_keeps_partial_record (c : Context P) :
    (closed c).record = record c ∧ (closed c).residual = residual c ∧
      (closed c).deferred = deferred c ∧ (closed c).dissent = dissent c :=
  ⟨rfl, rfl, rfl, rfl⟩

private theorem mem_recordOf {c : Context P} {x : Coordinate}
    {o : Occ (heldCoord (P := P) x) c} {r : Recorded c} (h : r ∈ recordOf x o) :
    r.coord = x ∧ isFilled o = true := by
  cases o with
  | open_ _ => simp [recordOf] at h
  | filled d s allowed supported =>
    simp only [recordOf, List.mem_singleton] at h
    subst h
    exact ⟨rfl, rfl⟩

theorem recorded_by_person (c : Context P) :
    ∀ r ∈ record c, r.src.src.val = .person ∧
      StandingSupported r.coord c (c[r.src.idx]'r.src.lt) r.det :=
  fun r _ => ⟨r.byPerson, r.supported⟩

theorem grant_never_self_granted (c : Context P) :
    ∀ r ∈ record c, r.det.standing = .granted → r.coord.kind ≠ .grant :=
  fun r _ => r.notSelfGrant

theorem suffix_without_person_is_no_source (c e : Context P) (he : ∀ t ∈ e, t.origin ≠ .person) :
    ∀ r ∈ record (c ++ e), r.src.idx < c.length := by
  intro r _
  refine Nat.lt_of_not_le fun hle => ?_
  have hok := r.src.ok
  rw [r.byPerson, List.getElem_append_right hle] at hok
  exact he _ (List.getElem_mem _) hok

theorem recorded_is_filled (c : Context P) (r : Recorded c) (h : r ∈ record c) :
    r.coord ∈ coordinates c ∧ isFilled (operative c r.coord) = true := by
  simp only [record, List.mem_flatMap] at h
  obtain ⟨x, hx, hr⟩ := h
  obtain ⟨hc, hf⟩ := mem_recordOf hr
  subst hc
  exact ⟨hx, hf⟩

theorem open_not_recorded (c : Context P) (x : Coordinate) (ho : isFilled (operative c x) = false)
    (r : Recorded c) (h : r ∈ record c) : r.coord ≠ x := by
  intro hx
  have := (recorded_is_filled c r h).2
  rw [hx, ho] at this
  cases this

theorem open_in_residual (c : Context P) (x : Coordinate) (hx : x ∈ coordinates c)
    (ho : isFilled (operative c x) = false) : x ∈ residual c := by
  simp [residual, hx, ho]

theorem held_only_by_person {c : Context P} {x : Coordinate} {s : Cite c}
    (ok : (heldCoord (P := P) x).admits s.src) : s.src.val = .person := ok

theorem taken_only_by_person {c : Context P} {s : Cite c}
    (ok : (resolutionCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem relayed_only_by_person {c : Context P} {s : Cite c}
    (ok : (relayCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem withdrawn_only_by_person {c : Context P} {s : Cite c}
    (ok : (withdrawalCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem feasibility_by_observation {c : Context P} {k : String} {s : Cite c}
    (ok : (feasibilityCoord (P := P) k).admits s.src) : s.src.val = .external := ok

end Hyphegesis
