module

public import Contract.Elenchus
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /sublate SKILL.md Lean block states; `Contract.Elenchus` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Elenchus

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Prospect := ⟨⟨"", []⟩⟩
instance : Nonempty Certificate := ⟨⟨[], List.nodup_nil, by simp, ""⟩⟩
instance : Nonempty ValueSpace := ⟨⟨⟨"", "", "", ""⟩, "", [], ⟨"", ""⟩⟩⟩
instance : Nonempty Tags := ⟨⟨⟨"", "", "", ""⟩, .provisionalAssumption, "", "", "", []⟩⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    sublate respond c [] = .holding c := by
  simp [sublate]

theorem unclosed_holds_gate (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Closable (pass (fuse c u))) :
    sublate respond c (u :: us) =
      sublate respond (pass (fuse c u) ++ [(respond (pass (fuse c u))).val]) us := by
  simp [sublate, h]

theorem start_holds (respond : Context P → Response P) (c : Context P) :
    start respond c [] = .holding (pass c ++ [(respond (pass c)).val]) := by
  simp [start, sublate]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t :=
  ⟨(tagReads c).map (·.val) ++ (passRecord (c ++ (tagReads c).map (·.val))).map (·.val), by
    simp [pass]⟩

theorem closes_after_utterance (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (v : VettedContext P) (h : sublate respond c us = .vetted v) :
    ∃ (c₀ : Context P) (u : Utterance P), v.context = pass (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [sublate] at h
  | cons u us ih =>
    simp only [sublate] at h
    split at h
    · unfold close at h
      split at h
      · cases h
      · cases h
      · cases h
        exact ⟨c, u, rfl⟩
    · exact ih _ h

theorem person_first (c : Context P) (a : Claim) (w : Answer)
    (h : filledValue (answer c a) = some w) : standing c a = .answered w := by
  simp [standing, h]

theorem unclear_waits (c : Context P) (a : Claim) (hr : filledValue (answer c a) = none)
    (hu : (certify c a).whose = .unclear) : standing c a = .open_ := by
  simp [standing, hr, hu]

theorem answered_by_person (c : Context P) (a : Claim) (w : Answer)
    (h : standing c a = .answered w) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  unfold standing at h
  cases hr : answer c a with
  | filled b src ok _ =>
    exact ⟨src, ok, src.ok.trans ok⟩
  | open_ _ =>
    simp only [hr, filledValue] at h
    split at h <;> cases h

theorem closing_by_person {c : Context P} {s : Cite c}
    (ok : (closeCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem vetted_closed_by_person (c : Context P) (v : VettedContext P) (hc : Closable c)
    (h : close c = .vetted v) : NothingOpen c ∧ PersonClosed c := by
  rcases hc with hs | ⟨t, ht⟩ | hn
  · simp [close, hs] at h
  · simp [close, ht] at h
  · exact hn

end Elenchus
