module

public import Contract.Elenchus
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /sublate SKILL.md Lean block states; `Contract.Elenchus` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Elenchus

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Prospect := ⟨⟨"", []⟩⟩
instance : Nonempty ValueSpace := ⟨⟨⟨"", "", "", ""⟩, "", [], ⟨"", ""⟩⟩⟩
instance : Nonempty Tags := ⟨⟨⟨"", "", "", ""⟩, .provisionalAssumption, "", "", "", []⟩⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    sublate respond c [] = .holding c := by
  simp [sublate]

theorem owed_holds_gate (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Vetted (pass (fuse c u))) :
    sublate respond c (u :: us) =
      sublate respond (pass (fuse c u) ++ [(respond (pass (fuse c u))).val]) us := by
  simp [sublate, h]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t :=
  ⟨(tagReads c).map (·.val) ++ (passRecord (c ++ (tagReads c).map (·.val))).map (·.val), by
    simp [pass]⟩

theorem closes_after_utterance (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (v : VettedContext P) (h : sublate respond c us = .vetted v) :
    ∃ (c₀ : Context P) (u : Utterance P), v.context = pass (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [sublate] at h
  | cons u us ih =>
    simp only [sublate] at h
    split at h
    · unfold close at h
      split at h
      · cases h
      · split at h
        · cases h
        · cases h
          exact ⟨c, u, rfl⟩
    · exact ih _ h

theorem person_route_is_route (c : Context P) (a : Audit) (d : Deficit)
    (h : filledValue (attribution c a.ref) = some (.route d)) : status c a = .route d := by
  simp [status, h]

theorem handed_not_judgment (c : Context P) (a : Audit) (r : DispositionRecord) (d : Deficit)
    (h : record c a = some r) (hd : r.disposition = .handed d) : r.assignedBy ≠ .judgment := by
  unfold record at h
  split at h
  · split at h
    · cases h; simp
    · cases h; simp
  · cases h; simp
  · cases hj : filledValue (judgment c a.ref) with
    | none => simp [hj] at h
    | some j =>
      simp [hj] at h
      subst h
      simp at hd
  · cases h

theorem attributed_by_person {c : Context P} {r : AuditRef} {s : Cite c}
    (ok : (attributionCoord (P := P) r).admits s.src) : s.src.val = .person := ok

theorem judged_by_person {c : Context P} {r : AuditRef} {s : Cite c}
    (ok : (judgmentCoord (P := P) r).admits s.src) : s.src.val = .person := ok

end Elenchus
