module

public import Contract.Analogia

/-! Proofs of the theorems the /ground SKILL.md Lean block states; `Contract.Analogia` is that block,
    generated by lean-contract.js. -/

public section

open Ground

namespace Analogia

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance {c : Context P} : Nonempty (Verdict c) := ⟨.undetermined ""⟩

theorem no_evidence_no_change (c : Context P) (h : observe c = []) : collect c = c := by
  simp [collect, h]

theorem narrowing_holds_at_gate (c : Context P) (hu : Uncertain c)
    (hn : UnsupportedNarrowing c) : report c = .focusGate := by
  simp [report, hu, hn]

theorem held_gate_collects_nothing (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hs : ¬ Supersedes (fuse c u))
    (hf : FocusHeld (fuse c u)) :
    ground respond c (u :: us) = ground respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [ground, hs, hf]

theorem assessment_converged (c : Context P) (h : report c = .assessment) :
    focusSettled c ∧ converged c := by
  unfold report at h
  split at h
  · cases h
  · split at h
    · cases h
    · rename_i h2
      split at h
      · cases h
      · split at h
        · cases h
        · split at h
          · rename_i h5
            refine ⟨?_, h5⟩
            apply Classical.byContradiction
            intro hn
            exact h2 (.inl hn)
          · cases h

theorem check_never_assent {c : Context P} {x : FitClaim} {scope : String} (s : Cite c)
    (ok : (checkCoord (P := P) x scope).admits s.kind) : s.kind ≠ .utterance := ok

theorem purpose_by_utterance {c : Context P} {s : Cite c}
    (ok : (axisCoord (P := P) .purpose).admits s.kind) : s.kind = .utterance := ok

theorem superseded_first (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : Supersedes (fuse c u)) :
    ground respond c (u :: us) = ⟨fuse c u, .superseded⟩ := by
  simp [ground, h]

end Analogia
