module

public import Contract.Analogia

/-! The theorems the /ground contract guarantees, each stated and proved here; `Contract.Analogia`
    is the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee
    the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Analogia

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance {c : Context P} : Nonempty (Verdict c) := ⟨.undetermined ""⟩
instance {c : Context P} {x : FitClaim} : Nonempty (Check c x) :=
  ⟨{ scope := "", wouldChangeIt := "", reach := none, state := .open_ none, more := [] }⟩

theorem no_evidence_no_change (c : Context P) (h : observe c = []) : collect c = c := by
  simp [collect, h]

/-- While the question does not stand, the pass presents it and collects nothing more. -/
theorem held_gate_collects_nothing (respond : Context P → Response P) (c : Context P)
    (h : ¬ QuestionStands c) : pass respond c = .holding c (respond c) := by
  simp [pass, h]

/-- The question is filled only from a person's turn. -/
theorem question_by_person {c : Context P} {s : Cite c}
    (ok : (questionCoord (P := P)).admits s.src) : s.src.val = .person := ok

/-- An assessment is made only over the collected context: the pass's question stood before
    collection, and the question that stands over the collected context is the one `hs`
    witnesses. -/
theorem assessment_after_collection (respond : Context P → Response P) (c b : Context P)
    (hs : QuestionStands b) (rec : Assessed b) (r : Response P)
    (h : pass respond c = .assessment b hs rec r) :
    b = collect c ∧ QuestionStands c := by
  unfold pass at h
  by_cases hc : QuestionStands c
  · by_cases hc₂ : QuestionStands (collect c)
    · simp [hc, hc₂] at h
      exact ⟨h.1.symm, hc⟩
    · simp [hc, hc₂] at h
  · simp [hc] at h

/-- An assessment's verdicts are `judge` over each conclusion of `K` in the collected context. -/
theorem assessment_verdicts_are_judge (respond : Context P → Response P) (c b : Context P)
    (hs : QuestionStands b) (rec : Assessed b) (r : Response P)
    (h : pass respond c = .assessment b hs rec r) :
    rec.verdicts = (inferences b).map fun k => (k, judge b k) := by
  unfold pass at h
  by_cases hc : QuestionStands c
  · by_cases hc₂ : QuestionStands (collect c)
    · simp [hc, hc₂] at h
      obtain ⟨hb, hrec, -⟩ := h
      subst hb
      cases hrec
      rfl
    · simp [hc, hc₂] at h
  · simp [hc] at h

/-- A pass whose question stands before and after collection yields the assessment. -/
theorem not_held_completes (respond : Context P → Response P) (c : Context P)
    (h₁ : QuestionStands c) (h₂ : QuestionStands (collect c)) :
    pass respond c = .assessment (collect c) h₂ (assessed (collect c)) (respond (collect c)) := by
  simp [pass, h₁, h₂]

/-- Silence settles nothing: with no utterance, the last outcome stands. -/
theorem silence_keeps_last (respond session : Context P → Response P) (c : Context P)
    (o : Outcome P) : ground respond session c o [] = o := rfl

/-- A turn that does not bear on the audit opens no pass: the session answers it, both stay in
    the context, and the last outcome stands — a waiting question stays open. -/
theorem unrelated_opens_no_pass (respond session : Context P → Response P) (c : Context P)
    (o : Outcome P) (u : Utterance P) (hb : ¬ BearsOnRun (fuse c u)) :
    step respond session c o u = (fuse c u ++ [(session (fuse c u)).val], o) := by
  simp [step, hb]

end Analogia
