module

public import Contract.Aitesis
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /inquire SKILL.md Lean block states; `Contract.Aitesis` is that block,
    generated by lean-contract.js. -/

public section

open Ground

namespace Aitesis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {c : Context P} {i : Item} : Nonempty (Landing c i) := ⟨.userUnknown .couldNot ""⟩

theorem state_unique {c : Context P} {i : Item} {s s' : State}
    (h : inState c s i) (h' : inState c s' i) : s = s' := h.2.symm.trans h'.2

theorem no_reentry (c : Context P) (i : Item) (hreg : Registered c i) (hself : SameItem c i i)
    (hd : (dismissal c i).isSome = true) : ¬ working c i := by
  rintro (⟨_, hn⟩ | ⟨_, hl⟩)
  · exact hn ⟨i, hreg, hself⟩
  · rw [hl] at hd; cases hd

theorem resolved_not_ai {c : Context P} {i : Item} {f w : String} {s : Cite c}
    {sup : LandSupported i c (c[s.idx]'s.lt) f} (_ : landing c i = .resolved f s sup w) :
    (c[s.idx]'s.lt).origin ≠ .assistant := by
  intro ho
  have hk := s.ok
  rw [ai_never_grounds _ ho] at hk
  cases hk

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t :=
  ⟨(push c).map (·.val) ++ (passRecord (c ++ (push c).map (·.val))).map (·.val), by
    simp [pass]⟩

theorem ends_sufficient {c c' : Context P} (h : CollectionEnds c c') :
    ∃ c₀, c' = pass c₀ ∧ (¬ PassChanged c₀ (pass c₀) ∨ ¬ WorthAnotherPass (pass c₀)) := by
  induction h with
  | stop c h => exact ⟨c, rfl, h⟩
  | more _ _ _ _ _ ih => exact ih

theorem sufficient_opens_no_pass (respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : answer (fuse c u) = some .sufficient) :
    inquire respond c (u :: us) = .declared (fuse c u) := by
  simp [inquire, h]

end Aitesis
