module

public import Contract.Aitesis
public import EpistemicProtocols.Ground.Theorems

/-! The theorems the /inquire contract guarantees, each stated and proved here; `Contract.Aitesis`
    is the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee
    the audit lists; a `private` theorem is a helper for one of them. The growth guarantees are
    proved over this contract's own operations; that the session is not cleared, compacted, or
    rewound between invocation and convergence is a harness event outside this contract, named in
    MORPHISM as its delegation point. -/

public section

open Ground

namespace Aitesis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem settled_not_ai (c : Context P) :
    ∀ r ∈ record c, (c[r.src.idx]'r.src.lt).origin ≠ .assistant :=
  fun r _ => cited_not_assistant r.src

theorem held_only_by_person (c : Context P) :
    ∀ r ∈ record c, r.settled.isHeld = true → r.src.src.val = .person :=
  fun r _ => r.heldByPerson

theorem dismissal_only_by_person {c : Context P} {x : Entry} {s : Cite c}
    (ok : (dismissalCoord (P := P) x).admits s.src) : s.src.val = .person := ok

theorem dismissed_by_person (c : Context P) : ∀ d ∈ dismissed c, d.src.src.val = .person :=
  fun d _ => d.byPerson

theorem silence_keeps_last_completion (respond session : Context P → Response P) (c : Context P)
    (r : SufficientContext P) : inquire respond session c r [] = r := by
  simp [inquire]

theorem other_work_collects_nothing (respond session : Context P → Response P) (c : Context P)
    (r : SufficientContext P) (u : Utterance P) (us : List (Utterance P))
    (h : ¬ Reaches (fuse c u)) :
    inquire respond session c r (u :: us) =
      inquire respond session (fuse c u ++ [(session (fuse c u)).val]) r us := by
  simp [inquire, h]

theorem reaching_collects_again (respond session : Context P → Response P) (c : Context P)
    (r : SufficientContext P) (u : Utterance P) (us : List (Utterance P))
    (h : Reaches (fuse c u)) :
    inquire respond session c r (u :: us) =
      inquire respond session (collectAndSettle respond (fuse c u)).closure.context
        (collectAndSettle respond (fuse c u)) us := by
  simp [inquire, h]

theorem completes_after_collection (respond : Context P → Response P) (c : Context P) :
    (collectAndSettle respond c).closure.context =
      collected c ++ [(respond (collected c)).val] := rfl

/-- Collection only adds to the context, over this contract's own operations. -/
theorem collected_extends (c : Context P) : ∃ t, collected c = c ++ t := ⟨_, rfl⟩

/-- A collection and its completion only add to the context, over this contract's own
    operations. -/
theorem settle_extends (respond : Context P → Response P) (c : Context P) :
    ∃ t, (collectAndSettle respond c).closure.context = c ++ t :=
  ⟨(collect c).map (·.val) ++ [(respond (collected c)).val], by simp [collectAndSettle, closed, collected]⟩

/-- Over this contract's own operations, a run either leaves the last completion standing or ends
    on a completion whose context extends the one it started from. -/
theorem inquire_extends (respond session : Context P → Response P) (c : Context P)
    (r : SufficientContext P) (us : List (Utterance P)) :
    inquire respond session c r us = r ∨
    ∃ t, (inquire respond session c r us).closure.context = c ++ t := by
  induction us generalizing c r with
  | nil => exact .inl (by simp [inquire])
  | cons u us ih =>
    by_cases hr : Reaches (fuse c u)
    · rw [reaching_collects_again respond session c r u us hr]
      obtain ⟨t, ht⟩ := settle_extends respond (fuse c u)
      rcases ih (collectAndSettle respond (fuse c u)).closure.context
          (collectAndSettle respond (fuse c u)) with h | ⟨t', ht'⟩
      · exact .inr ⟨[u.val] ++ t, by rw [h, ht]; simp [fuse]⟩
      · exact .inr ⟨[u.val] ++ t ++ t', by rw [ht', ht]; simp [fuse]⟩
    · rw [other_work_collects_nothing respond session c r u us hr]
      rcases ih (fuse c u ++ [(session (fuse c u)).val]) r with h | ⟨t', ht'⟩
      · exact .inl h
      · exact .inr ⟨[u.val, (session (fuse c u)).val] ++ t', by rw [ht']; simp [fuse]⟩

/-- A run's completion extends the context it was invoked on, over this contract's own
    operations. -/
theorem start_extends (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) :
    ∃ t, (start respond session c us).closure.context = c ++ t := by
  obtain ⟨t, ht⟩ := settle_extends respond c
  rcases inquire_extends respond session (collectAndSettle respond c).closure.context
      (collectAndSettle respond c) us with h | ⟨t', ht'⟩
  · exact ⟨t, by simp only [start]; rw [h, ht]⟩
  · exact ⟨t ++ t', by simp only [start]; rw [ht', ht]; simp⟩

theorem never_holds_the_turn (op : Op) (k : ToolGrounding.Interaction)
    (h : (grounding op).1 = .interaction k) : k.realization = .proceed := by
  cases op <;> simp [grounding] at h <;> subst h <;> rfl

end Aitesis
