module

public import Contract.Proplasma
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /preview SKILL.md Lean block states; `Contract.Proplasma` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Proplasma

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Contrast := ⟨⟨[], [], []⟩⟩
instance : Nonempty Verdict := ⟨.withdraw⟩

theorem silence (ai : AITurns P) (c : Context P) : preview ai c [] = .holding c := by
  simp [preview]

theorem relay_before_instantiation (ai : AITurns P) (c : Context P) :
    ∃ t, fan ai c = c ++ [(ai.relay c).val] ++ t := by
  unfold fan
  simp only [List.append_assoc]
  exact ⟨_, rfl⟩

theorem spent_budget_no_refan (ai : AITurns P) (c : Context P) (h : ¬ BudgetLeft c) :
    insufficiencyArms ai c = spentArms c := by
  simp [insufficiencyArms, h]

theorem materialize_unavailable (ai : AITurns P) (c c' : Context P)
    (hv : verdict c' = .materialize) (hb : ¬ BudgetLeft c') : step ai c c' = .gate c' := by
  simp [step, hv, hb]

theorem harvest_before_discard (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : DirectionalContrast P) (h : preview ai c us = .contrasted r) :
    ∃ c₀, harvestOf c₀ = some r.harvest ∧ r.context = discard c₀ := by
  have spent : ∀ c₁, spentArms (P := P) c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold spentArms at hs
    split at hs <;> (split at hs <;> cases hs)
  have arms : ∀ c₁, insufficiencyArms ai c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold insufficiencyArms at hs
    split at hs
    · dsimp only at hs
      split at hs
      · exact spent _ hs
      · cases hs
    · exact spent _ hs
  have after : ∀ c₁, afterFan ai c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold afterFan at hs
    split at hs
    · exact arms _ hs
    · cases hs
  have key : ∀ c₁ c₂, step ai c₁ c₂ = .done (.contrasted r) →
      ∃ c₀, harvestOf c₀ = some r.harvest ∧ r.context = discard c₀ := by
    intro c₁ c₂ hs
    unfold step at hs
    split at hs
    · split at hs
      · rename_i hh
        simp only [constituted] at hs
        cases hs
        exact ⟨c₂, hh, rfl⟩
      · cases hs
    · cases hs
    · cases hs
    · split at hs
      · exact absurd hs (after _)
      · cases hs
    · split at hs
      · exact absurd hs (arms _)
      · exact absurd hs (after _)
    · exact absurd hs (arms _)
    · split at hs
      · exact absurd hs (after _)
      · cases hs
    · cases hs
    · cases hs
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · exact ih _ h
    · rename_i o hs
      cases h
      exact key _ _ hs

theorem dissolved_by_person (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (c₁ : Context P) (d : List String) (h : preview ai c us = .dissolved c₁ d) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .dissolve ∧ c₁ = discard (fuse c₀ u) := by
  have spent : ∀ c₂, spentArms (P := P) c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold spentArms at hs
    split at hs <;> (split at hs <;> cases hs)
  have arms : ∀ c₂, insufficiencyArms ai c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold insufficiencyArms at hs
    split at hs
    · dsimp only at hs
      split at hs
      · exact spent _ hs
      · cases hs
    · exact spent _ hs
  have after : ∀ c₂, afterFan ai c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold afterFan at hs
    split at hs
    · exact arms _ hs
    · cases hs
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · exact ih _ h
    · rename_i o hs
      cases h
      unfold step at hs
      split at hs
      · split at hs
        · simp only [constituted] at hs
          cases hs
        · cases hs
      · cases hs
      · cases hs
      · split at hs
        · exact absurd hs (after _)
        · cases hs
      · split at hs
        · exact absurd hs (arms _)
        · exact absurd hs (after _)
      · exact absurd hs (arms _)
      · split at hs
        · exact absurd hs (after _)
        · cases hs
      · rename_i hv
        cases hs
        exact ⟨c, u, hv, rfl⟩
      · cases hs

theorem direction_by_person {c : Context P} {s : Cite c}
    (ok : (directionCoord (P := P)).admits s.src) : s.src.val = .person := ok

end Proplasma
