module

public import Contract.Proplasma

/-! Proofs of the theorems the /preview SKILL.md Lean block states; `Contract.Proplasma` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Proplasma

variable {P : Type}

theorem silence (relay respond : Context P → Response P) (c : Context P) :
    preview relay respond c [] = .holding c := by
  simp [preview]

theorem relay_before_instantiation (relay : Context P → Response P) (c : Context P) :
    ∃ t, fan relay c = c ++ [(relay c).val] ++ t :=
  ⟨_, rfl⟩

theorem spent_budget_no_refan (relay : Context P → Response P) (c : Context P)
    (h : ¬ BudgetLeft c) : insufficiencyArms relay c = spentArms c := by
  simp [insufficiencyArms, h]

theorem materialize_unavailable (relay : Context P → Response P) (c c' : Context P)
    (hv : verdict c' = .materialize) (hb : ¬ BudgetLeft c') : step relay c c' = .gate c' := by
  simp [step, hv, hb]

theorem harvest_before_discard (relay respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : DirectionalContrast P)
    (h : preview relay respond c us = .contrasted r) :
    ∃ c₀, harvestOf c₀ = some r.harvest ∧ r.context = discard c₀ := by
  have spent : ∀ c₁, spentArms (P := P) c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold spentArms at hs
    split at hs <;> (split at hs <;> cases hs)
  have arms : ∀ c₁, insufficiencyArms relay c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold insufficiencyArms at hs
    split at hs
    · dsimp only at hs
      split at hs
      · exact spent _ hs
      · cases hs
    · exact spent _ hs
  have after : ∀ c₁, afterFan relay c₁ ≠ .done (.contrasted r) := by
    intro c₁ hs
    unfold afterFan at hs
    split at hs
    · exact arms _ hs
    · cases hs
  have key : ∀ c₁ c₂, step relay c₁ c₂ = .done (.contrasted r) →
      ∃ c₀, harvestOf c₀ = some r.harvest ∧ r.context = discard c₀ := by
    intro c₁ c₂ hs
    unfold step at hs
    split at hs
    · split at hs
      · rename_i hh
        cases hs
        exact ⟨c₂, hh, rfl⟩
      · cases hs
    · cases hs
    · cases hs
    · split at hs
      · exact absurd hs (after _)
      · cases hs
    · split at hs
      · exact absurd hs (arms _)
      · exact absurd hs (after _)
    · exact absurd hs (arms _)
    · split at hs
      · exact absurd hs (after _)
      · cases hs
    · cases hs
    · cases hs
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · exact ih _ h
    · rename_i o hs
      cases h
      exact key _ _ hs

theorem dissolved_by_person (relay respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (d : List String)
    (h : preview relay respond c us = .dissolved c₁ d) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .dissolve ∧ c₁ = discard (fuse c₀ u) := by
  have spent : ∀ c₂, spentArms (P := P) c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold spentArms at hs
    split at hs <;> (split at hs <;> cases hs)
  have arms : ∀ c₂, insufficiencyArms relay c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold insufficiencyArms at hs
    split at hs
    · dsimp only at hs
      split at hs
      · exact spent _ hs
      · cases hs
    · exact spent _ hs
  have after : ∀ c₂, afterFan relay c₂ ≠ .done (.dissolved c₁ d) := by
    intro c₂ hs
    unfold afterFan at hs
    split at hs
    · exact arms _ hs
    · cases hs
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · exact ih _ h
    · rename_i o hs
      cases h
      unfold step at hs
      split at hs
      · split at hs
        · cases hs
        · cases hs
      · cases hs
      · cases hs
      · split at hs
        · exact absurd hs (after _)
        · cases hs
      · split at hs
        · exact absurd hs (arms _)
        · exact absurd hs (after _)
      · exact absurd hs (arms _)
      · split at hs
        · exact absurd hs (after _)
        · cases hs
      · rename_i hv
        cases hs
        exact ⟨c, u, hv, rfl⟩
      · cases hs

theorem direction_by_utterance {c : Context P} {s : Cite c}
    (ok : (directionCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

end Proplasma
