module

public import Contract.Proplasma
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /preview SKILL.md Lean block states; `Contract.Proplasma` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Proplasma

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Contrast := ⟨⟨[], [], []⟩⟩

theorem silence (ai : AITurns P) (c : Context P) : preview ai c [] = .holding c := by
  simp [preview]

theorem relay_before_instantiation (ai : AITurns P) (c : Context P) :
    ∃ t, fan ai c = c ++ [(ai.relay c).val] ++ t := by
  unfold fan
  simp only [List.append_assoc]
  exact ⟨_, rfl⟩

theorem contrasted_on_constitute (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : DirectionalContrast P) (h : preview ai c us = .contrasted r) :
    ∃ (c₁ : Context P) (d : Direction), filledValue (closing c₁) = some (.constitute d) ∧
      Covered c₁ ∧ r.harvest = harvestOf c₁ d ∧ r.context = discard c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · rename_i d hk
      split at h
      · rename_i hc
        cases h
        exact ⟨_, d, hk, hc, rfl, rfl⟩
      · exact ih _ h
    · cases h
    · cases h
    · cases h
    · exact ih _ h

theorem dissolved_on_dissolve (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : Closed P) (h : preview ai c us = .dissolved r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .dissolve ∧ r = closed c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · split at h
      · cases h
      · exact ih _ h
    · rename_i hk
      cases h
      exact ⟨_, hk, rfl⟩
    · cases h
    · cases h
    · exact ih _ h

theorem withdrawn_on_stop (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : Closed P) (h : preview ai c us = .withdrawn r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .stop ∧ r = closed c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · split at h
      · cases h
      · exact ih _ h
    · cases h
    · rename_i hk
      cases h
      exact ⟨_, hk, rfl⟩
    · cases h
    · exact ih _ h

theorem routed_on_route (ai : AITurns P) (c : Context P) (us : List (Utterance P)) (t : String)
    (r : Closed P) (h : preview ai c us = .routed t r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some (.route t) ∧ r = closed c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    simp only [preview] at h
    split at h
    · split at h
      · cases h
      · exact ih _ h
    · cases h
    · cases h
    · rename_i t' hk
      cases h
      exact ⟨_, hk, rfl⟩
    · exact ih _ h

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem trace_total (c : Context P) : (discardTrace c).length = (probes c).length := by
  simp [discardTrace]

end Proplasma
