module

public import Contract.Proplasma
public import EpistemicProtocols.Ground.Theorems

/-! The theorems the /preview contract guarantees, each stated and proved here; `Contract.Proplasma`
    is the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee
    the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Proplasma

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (ai : AITurns P) (c : Context P) : preview ai c [] = .holding c := by
  simp [preview]

theorem relay_before_instantiation (ai : AITurns P) (c : Context P) :
    ∃ t, fan ai c = c ++ [(ai.relay c).val] ++ t := by
  unfold fan
  simp only [List.append_assoc]
  exact ⟨_, rfl⟩

theorem unrelated_adds_no_gate (ai : AITurns P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Reaches (fuse c u)) :
    preview ai c (u :: us) = preview ai (fuse c u ++ [(ai.session (fuse c u)).val]) us := by
  simp [preview, h]

/-- One step either continues on some context or ends at a closing the person's turn filled. -/
private theorem step (ai : AITurns P) (c : Context P) (u : Utterance P) (us : List (Utterance P))
    (o : Outcome P) (h : preview ai c (u :: us) = o) :
    (∃ c', preview ai c' us = o) ∨
    (∃ d, filledValue (closing (fuse c u)) = some (.constitute d) ∧
      o = .contrasted (constituted (fuse c u) d)) ∨
    (filledValue (closing (fuse c u)) = some .dissolve ∧ o = .dissolved (closed (fuse c u))) ∨
    (filledValue (closing (fuse c u)) = some .withdraw ∧ o = .withdrawn (closed (fuse c u))) := by
  simp only [preview] at h
  split at h
  · exact .inl ⟨_, h⟩
  · split at h
    · rename_i d hk
      exact .inr (.inl ⟨d, hk, h.symm⟩)
    · rename_i hk
      exact .inr (.inr (.inl ⟨hk, h.symm⟩))
    · rename_i hk
      exact .inr (.inr (.inr ⟨hk, h.symm⟩))
    · exact .inl ⟨_, h⟩

theorem contrasted_on_constitute (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : DirectionalContrast P) (h : preview ai c us = .contrasted r) :
    ∃ (c₁ : Context P) (d : Direction), filledValue (closing c₁) = some (.constitute d) ∧
      r.harvest = harvestOf c₁ d ∧ r.context = discard c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    rcases step ai c u us _ h with ⟨c', h'⟩ | ⟨d, hk, h'⟩ | ⟨_, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, d, hk, rfl, rfl⟩
    · cases h'
    · cases h'

theorem dissolved_on_dissolve (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : Closed P) (h : preview ai c us = .dissolved r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .dissolve ∧ r = closed c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    rcases step ai c u us _ h with ⟨c', h'⟩ | ⟨_, _, h'⟩ | ⟨hk, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨_, hk, rfl⟩
    · cases h'

theorem withdrawn_on_withdraw (ai : AITurns P) (c : Context P) (us : List (Utterance P))
    (r : Closed P) (h : preview ai c us = .withdrawn r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .withdraw ∧ r = closed c₁ := by
  induction us generalizing c with
  | nil => simp [preview] at h
  | cons u us ih =>
    rcases step ai c u us _ h with ⟨c', h'⟩ | ⟨_, _, h'⟩ | ⟨_, h'⟩ | ⟨hk, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
    · cases h'
      exact ⟨_, hk, rfl⟩

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem check_only_when_asked (c : Context P) (h : Op.check ∈ consultOps c) : AsksCheck c :=
  Classical.byContradiction fun hn => by simp [consultOps, hn] at h

theorem trace_total (c : Context P) : (discardTrace c).length = (probes c).length := by
  simp [discardTrace]

end Proplasma
