module

public import Contract.Periagoge
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /induce SKILL.md Lean block states; `Contract.Periagoge` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Periagoge

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Candidate := ⟨⟨"", "", "", none⟩⟩
instance : Nonempty Row := ⟨⟨"", ⟨"", ⟨"", ""⟩⟩, ⟨"", ⟨"", ""⟩⟩, ""⟩⟩
instance : Nonempty Move := ⟨.confirm⟩
instance : Nonempty CaseUnfolding := ⟨⟨"", "", "", "", ""⟩⟩

theorem silence (respond declare : Context P → Response P) (c : Context P) :
    induce respond declare c [] = .holding c := by
  simp [induce]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  let c₁ := c ++ (collect c).map (·.val)
  exact ⟨(collect c).map (·.val) ++ (passRecord c₁).map (·.val), by simp [pass, c₁]⟩

theorem crystallized_on_confirm (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : CrystallizedAbstraction P)
    (h : induce respond declare c us = .crystallized r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .confirm ∧ CandidateLive c₁ ∧ Covered c₁ ∧
      r = crystallize declare c₁ := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · cases h
      · cases h
      · rename_i hk
        split at h
        · rename_i hc
          cases h
          exact ⟨_, hk, hc.1, hc.2, rfl⟩
        · exact ih _ h
      · exact ih _ h

theorem withdrawn_on_stop (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Withdrawn P) (h : induce respond declare c us = .withdrawn r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .stop ∧ r = withdraw declare c₁ := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · rename_i hk
        cases h
        exact ⟨_, hk, rfl⟩
      · cases h
      · split at h
        · cases h
        · exact ih _ h
      · exact ih _ h

theorem routed_on_route (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (t : String) (r : Withdrawn P)
    (h : induce respond declare c us = .routed t r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some (.route t) ∧ r = withdraw declare c₁ := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · cases h
      · rename_i hk
        cases h
        exact ⟨_, hk, rfl⟩
      · split at h
        · cases h
        · exact ih _ h
      · exact ih _ h

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem live_reading_crossed (c : Context P) (r : Reading) (h : r ∈ live c) :
    (r, row c r) ∈ crossView c := by
  simp only [crossView, List.mem_map]
  exact ⟨r, h, rfl⟩

theorem live_leaves_only_by_person (c : Context P) (r : Reading) (hr : r ∈ readings c)
    (hn : r ∉ live c) : ∃ g, filledValue (setAside c r) = some g := by
  unfold live at hn
  simp only [List.mem_filter, not_and] at hn
  have := hn hr
  cases hs : filledValue (setAside c r) with
  | none => simp_all
  | some g => exact ⟨g, rfl⟩

theorem row_cases_unfolded (c : Context P) (i : Instance) (h : i ∈ rowCases c) :
    (i, unfoldCase c i) ∈ casesSection c := by
  simp only [casesSection, List.mem_map]
  exact ⟨i, h, rfl⟩

theorem shown_candidate_live (c : Context P) (k : Candidate) (h : shownCandidate c = some k) :
    k.reading ∈ live c := by
  unfold shownCandidate at h
  split at h
  · rename_i hl
    cases h
    exact hl
  · cases h

theorem exhausted_when_none_live (c : Context P) (h : live c = []) : focus c = .exhausted := by
  simp [focus, h]

theorem nothing_adopted_before_confirm (c : Context P) (p : Provenance) (h : p ∈ provenance c) :
    p.standing ≠ .adopted := by
  simp only [provenance, List.mem_map] at h
  obtain ⟨e, _, rfl⟩ := h
  simp only [standing]
  split <;> simp

theorem set_aside_by_person {c : Context P} {r : Reading} {s : Cite c}
    (ok : (setAsideCoord (P := P) r).admits s.src) : s.src.val = .person := ok

theorem disposed_by_person {c : Context P} {i : OpenItem} {s : Cite c}
    (ok : (dispositionCoord (P := P) i).admits s.src) : s.src.val = .person := ok

end Periagoge
