module

public import Contract.Periagoge
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /induce SKILL.md Lean block states; `Contract.Periagoge` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Periagoge

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond declare : Context P → Response P) (c : Context P) :
    induce respond declare c [] = .holding c := by
  simp [induce]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  let c₁ := c ++ (collect c).map (·.val)
  exact ⟨(collect c).map (·.val) ++ (passRecord c₁).map (·.val), by simp [pass, c₁]⟩

theorem proposal_only_when_showable (c : Context P) (n : Naming) (h : shownNaming c = some n) :
    Showable c := by
  unfold shownNaming at h
  split at h
  · assumption
  · cases h

theorem crystallized_on_confirm (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : CrystallizedAbstraction P)
    (h : induce respond declare c us = .crystallized r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .confirm ∧ shownNaming c₁ = some r.naming ∧
      Showable c₁ ∧ Covered c₁ ∧ r = crystallize declare c₁ r.naming := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · cases h
      · cases h
      · rename_i hk
        split at h
        · rename_i n hn
          split at h
          · rename_i hc
            cases h
            exact ⟨_, hk, hn, proposal_only_when_showable _ _ hn, hc, rfl⟩
          · exact ih _ h
        · exact ih _ h
      · exact ih _ h

theorem withdrawn_on_stop (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Withdrawn P) (h : induce respond declare c us = .withdrawn r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .stop ∧ r = withdraw declare c₁ := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · rename_i hk
        cases h
        exact ⟨_, hk, rfl⟩
      · cases h
      · split at h
        · split at h
          · cases h
          · exact ih _ h
        · exact ih _ h
      · exact ih _ h

theorem routed_on_route (respond declare : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (t : String) (r : Withdrawn P)
    (h : induce respond declare c us = .routed t r) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some (.route t) ∧ r = withdraw declare c₁ := by
  induction us generalizing c with
  | nil => simp [induce] at h
  | cons u us ih =>
    simp only [induce] at h
    split at h
    · exact ih _ h
    · split at h
      · cases h
      · rename_i hk
        cases h
        exact ⟨_, hk, rfl⟩
      · split at h
        · split at h
          · cases h
          · exact ih _ h
        · exact ih _ h
      · exact ih _ h

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem cap_bounds_draws (c : Context P) (h : CapReached c) : draw c = none := by
  simp [draw, h]

theorem verdict_by_person {c : Context P} {p : ProbeCase} {r : Reading} {s : Cite c}
    (ok : (verdictCoord (P := P) p r).admits s.src) : s.src.val = .person := ok

theorem disposed_by_person {c : Context P} {i : OpenItem} {s : Cite c}
    (ok : (dispositionCoord (P := P) i).admits s.src) : s.src.val = .person := ok

end Periagoge
