module

public import Contract.Anamnesis
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /recollect SKILL.md Lean block states; `Contract.Anamnesis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Anamnesis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance : Nonempty Cue := ⟨⟨"", .session, []⟩⟩
instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    recollect respond c [] = .holding c := by
  simp [recollect]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t :=
  ⟨(search c).map (·.val) ++ (passRecord (c ++ (search c).map (·.val))).map (·.val), by
    simp [pass]⟩

theorem invocation_activates (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (h : Invoked c) : start respond c us ≠ .notActivated c := by
  have hs : ∀ (d : Context P) (o : Outcome P), settle d = some o → o ≠ .notActivated c := by
    intro d o ho
    unfold settle at ho
    split at ho
    · cases ho; simp
    · cases ho
  have hc : ∀ (d : Context P) (o : Outcome P), closing d = some o → o ≠ .notActivated c := by
    intro d o ho
    unfold closing at ho
    split at ho
    · cases ho; simp
    · cases ho; simp
    · cases ho
  have key : ∀ (us : List (Utterance P)) (d : Context P),
      recollect respond d us ≠ .notActivated c := by
    intro us
    induction us with
    | nil => intro d; simp [recollect]
    | cons u us ih =>
      intro d
      simp only [recollect]
      split
      · next o ho => exact hc _ o ho
      · split
        · next o ho => exact hs _ o ho
        · exact ih _
  have ha : Activated c := Or.inl h
  unfold start
  simp only [ha, ↓reduceIte]
  split
  · next o ho => exact hs _ o ho
  · exact key _ _

theorem identified_by_person (c : Context P) (v : RecalledContext P)
    (h : closing c = some (.identified v)) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  unfold closing at h
  cases hA : answer c with
  | open_ x =>
    rw [hA] at h
    simp at h
  | filled a s ok _ => exact ⟨s, ok, s.ok.trans ok⟩

theorem answer_by_person {c : Context P} {s : Cite c}
    (ok : (answerCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem claim_is_evidence {c : Context P} (k : Claim c) :
    (c[k.src.idx]'k.src.lt).origin ≠ .assistant ∧ k.src.src.val ≠ .person :=
  ⟨cited_not_assistant k.src, k.evidence⟩

theorem unresolved_after_cue (c c' : Context P) (s : String)
    (h : settle c = some (.unresolved c' s)) : AddedToCue c := by
  unfold settle at h
  split at h
  · next hc => exact hc.2.1
  · cases h

end Anamnesis
