module

public import Contract.Horismos

/-! Proofs of the theorems the /bound SKILL.md Lean block states; `Contract.Horismos` is that block,
    generated by lean-contract.js. -/

public section

open Ground

namespace Horismos

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {c : Context P} : Nonempty (BoundaryEssence c) := ⟨⟨[], [], "", [], []⟩⟩
instance : Nonempty Verdict := ⟨.cont⟩
variable (respond : Context P → Response P)

theorem silence (c : Context P) : bound respond c [] = .holding c := rfl

theorem continue_folds (c : Context P) (xs ys : List (Utterance P))
    (h : AllCont respond c xs) :
    bound respond c (xs ++ ys) = bound respond (foldRounds respond c xs) ys := by
  induction xs generalizing c with
  | nil => rfl
  | cons u us ih =>
    simp only [AllCont] at h
    simp only [List.cons_append, bound, h.1, foldRounds]
    exact ih _ h.2

theorem stop_here (c : Context P) (u : Utterance P) (us : List (Utterance P))
    (h : verdict (fuse c u) = .finish) :
    bound respond c (u :: us) = .defined (close (fuse c u)) := by
  simp [bound, h]

theorem defined_ends_in_utterance (c : Context P) (us : List (Utterance P))
    (b : DefinedBoundary P) (h : bound respond c us = .defined b) :
    ∃ (c₀ : Context P) (u : Utterance P), b.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [bound] at h
  | cons u us ih =>
    simp only [bound] at h
    split at h
    · exact ih _ h
    · cases h; exact ⟨c, u, rfl⟩
    · cases h
    · cases h

end Horismos
