module

public import Contract.Horismos

/-! The theorems the /bound contract guarantees, each stated and proved here; `Contract.Horismos` is
    the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee the
    audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Horismos

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {c : Context P} : Nonempty (BoundaryEssence c) := ⟨⟨[], ""⟩⟩
instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

variable (respond session : Context P → Response P)

/-- Silence settles nothing: with no further utterance the run stands as it was — a holding gate
    keeps holding, a boundary that stands keeps standing. -/
theorem silence (c : Context P) (o : Outcome P) : bound respond session c o [] = o := by
  cases o <;> simp [bound]

/-- A run that has withdrawn stays withdrawn: later words do not revive it. -/
theorem withdrawn_stays (c : Context P) (w : Withdrawal P) (us : List (Utterance P)) :
    bound respond session c (.withdrawn w) us = .withdrawn w := by
  cases us <;> simp [bound]

/-- The run opens by reading the invoking context with what observation returned: where nothing
    awaits the person and no turn of theirs is owed, the boundary stands at once and the first turn
    shows it (`converge`); otherwise the gate holds with the first round in its context. No
    boundary stood before the run. -/
theorem start_reads_first (c : Context P) (us : List (Utterance P)) :
    start respond session c us =
      bound respond session (observed c ++ [(respond (observed c)).val])
        (status (observed c) (observed c ++ [(respond (observed c)).val]) none) us :=
  rfl

/-- An utterance that does not bear on the boundary adds no round and leaves how the run stands as
    it stood; a gate that holds holds the context as it now stands. -/
theorem unrelated_keeps_the_run (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (ho : ∀ w, o ≠ .withdrawn w) (h : ¬ Reaches (fuse c u)) :
    bound respond session c o (u :: us) =
      bound respond session (fuse c u ++ [(session (fuse c u)).val])
        (o.carry (fuse c u ++ [(session (fuse c u)).val])) us := by
  cases o with
  | withdrawn w => exact absurd rfl (ho w)
  | _ => simp [bound, h]

/-- Carrying the run to a longer context keeps what it is: a boundary that stands stays the same
    boundary, a withdrawal stays the same record, and a gate that holds keeps the boundary that
    last stood. -/
theorem carry_keeps_status (o : Outcome P) (c : Context P) :
    (o.carry c).stood = o.stood ∧
      (∀ b, o = .defined b → o.carry c = .defined b) ∧
      (∀ w, o = .withdrawn w → o.carry c = .withdrawn w) := by
  cases o <;> simp [Outcome.carry, Outcome.stood]

/-- A withdrawal — at the person's word, or once observation settles its reading — ends the run
    there: its record keeps the snapshot at that word and, apart from it, the boundary that last
    stood; it sets no boundary from there. -/
theorem withdrawal_at_word (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (ho : ∀ w, o ≠ .withdrawn w) (hr : Reaches (fuse c u))
    (h : isFilled (withdrawal (fuse c u)) = true ∨
      isFilled (withdrawal (observed (fuse c u))) = true) :
    bound respond session c o (u :: us) =
      .withdrawn ⟨snapshotOf (fuse c u), o.stood⟩ := by
  cases o with
  | withdrawn w => exact absurd rfl (ho w)
  | _ => rcases h with h | h <;> simp [bound, hr, h]

/-- Any other utterance that bears on the boundary is read where it is said, with what observation
    returned — the run stands as that leaves it — and then answered by your turn, and a gate that
    holds holds with that turn in its context and the boundary that last stood; also after the
    boundary stood, so a later correction reopens it. -/
theorem bearing_utterance_rounds (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (ho : ∀ w, o ≠ .withdrawn w) (hr : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false)
    (hw' : isFilled (withdrawal (observed (fuse c u))) = false) :
    bound respond session c o (u :: us) =
      bound respond session (observed (fuse c u) ++ [(respond (observed (fuse c u))).val])
        (status (observed (fuse c u))
          (observed (fuse c u) ++ [(respond (observed (fuse c u))).val]) o.stood) us := by
  cases o with
  | withdrawn w => exact absurd rfl (ho w)
  | _ => simp [bound, hr, hw, hw']

/-- The boundary stands only where no turn of the person's is owed, and then on one of two grounds:
    the person's acceptance, or, without it, no item awaiting their disposition; it is read at
    `c`, with its limits and dissent read with the turn that shows it. -/
theorem defined_grounds (c shown : Context P) (stood : Option (DefinedBoundary P))
    (b : DefinedBoundary P) (h : status c shown stood = .defined b) :
    owed c = false ∧
      (isFilled (acceptance c) = true ∨ awaits (readout c) = false) ∧
      b = closeAt c shown (readout c) := by
  unfold status at h
  dsimp only at h
  split at h
  · rename_i hc
    cases h
    simp only [Bool.and_eq_true, Bool.or_eq_true, Bool.not_eq_true'] at hc
    exact ⟨hc.1, hc.2, rfl⟩
  · cases h

/-- Where a turn of the person's is still owed, the gate holds, with the round that serves it in
    its context and the boundary that last stood. -/
theorem owed_holds (c shown : Context P) (stood : Option (DefinedBoundary P))
    (h : owed c = true) : status c shown stood = .holding shown stood := by
  simp [status, h]

/-- A gate that holds keeps the boundary that last stood: a reopen erases nothing a later
    withdrawal must show. -/
theorem reopen_keeps_what_stood (c shown : Context P) (stood : Option (DefinedBoundary P))
    (c' : Context P) (s : Option (DefinedBoundary P)) (h : status c shown stood = .holding c' s) :
    s = stood := by
  unfold status at h
  dsimp only at h
  split at h
  · cases h
  · cases h; rfl

/-- What observation joins to a context is evidence: no turn of yours, and no person's turn. -/
theorem observed_adds_evidence (c : Context P) :
    ∃ ev : List (Turn P), observed c = c ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer := by
  refine ⟨(observe c).map (·.val), rfl, ?_⟩
  intro e he
  simp only [List.mem_map] at he
  obtain ⟨x, _, rfl⟩ := he
  exact x.property

/-- Wherever the boundary stands, it is read before your turn: the context it closes is the one
    read — at the person's utterance, or at the start the invoking context — with only what
    observation returned after it. -/
theorem defined_before_your_turn (c shown : Context P) (stood : Option (DefinedBoundary P))
    (b : DefinedBoundary P) (h : status (observed c) shown stood = .defined b) :
    ∃ ev : List (Turn P), b.snapshot.context = c ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer := by
  obtain ⟨_, _, rfl⟩ := defined_grounds (observed c) shown stood b h
  exact observed_adds_evidence c

/-- Where a person's utterance sets the boundary, the boundary is read at that utterance: the
    context it closes is the person's turn followed only by what observation returned. -/
theorem defined_at_utterance (c : Context P) (u : Utterance P) (shown : Context P)
    (stood : Option (DefinedBoundary P)) (b : DefinedBoundary P)
    (h : status (observed (fuse c u)) shown stood = .defined b) :
    ∃ ev : List (Turn P), b.snapshot.context = c ++ [u.val] ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer :=
  defined_before_your_turn (fuse c u) shown stood b h

/-- A boundary that a bearing utterance sets is read at that utterance: the context it closes is
    the person's turn followed only by what observation returned. -/
theorem defined_ends_in_utterance (c : Context P) (o : Outcome P) (u : Utterance P)
    (ho : ∀ w, o ≠ .withdrawn w) (hr : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false)
    (hw' : isFilled (withdrawal (observed (fuse c u))) = false)
    (b : DefinedBoundary P) (h : bound respond session c o [u] = .defined b) :
    ∃ ev : List (Turn P), b.snapshot.context = c ++ [u.val] ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer := by
  rw [bearing_utterance_rounds respond session c o u [] ho hr hw hw', silence] at h
  exact defined_at_utterance c u _ _ b h

/-- Only a person's turn accepts the boundary. -/
theorem accepted_only_by_person (g : Grounding) (h : (acceptanceCoord (P := P)).admits g) :
    g.val = .person := h

/-- Only a person's turn withdraws. -/
theorem withdrawn_only_by_person (g : Grounding) (h : (withdrawalCoord (P := P)).admits g) :
    g.val = .person := h

/-- An acceptance sets the boundary whatever is still open; the open part is its residual. -/
theorem acceptance_sets_despite_residual (c shown : Context P) (stood : Option (DefinedBoundary P))
    (ho : owed c = false) (h : isFilled (acceptance c) = true) :
    status c shown stood = .defined (closeAt c shown (readout c)) := by
  simp [status, h, ho]

/-- Where something awaits the person and they have not accepted, the gate holds. -/
theorem awaiting_holds (c shown : Context P) (stood : Option (DefinedBoundary P))
    (ha : isFilled (acceptance c) = false) (hw : awaits (readout c) = true) :
    status c shown stood = .holding shown stood := by
  simp [status, ha, hw]

/-- Each utterance either continues the run — a later step carries it — or withdraws it, at the
    person's word or once observation settles its reading, with the record at that word. -/
theorem each_step_continues_or_withdraws (c : Context P) (o r : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (ho : ∀ w, o ≠ .withdrawn w)
    (h : bound respond session c o (u :: us) = r) :
    (∃ c' o', bound respond session c' o' us = r) ∨
    ((isFilled (withdrawal (fuse c u)) = true ∨
        isFilled (withdrawal (observed (fuse c u))) = true) ∧
      r = .withdrawn ⟨snapshotOf (fuse c u), o.stood⟩) := by
  cases o with
  | withdrawn w => exact absurd rfl (ho w)
  | _ =>
    simp only [bound] at h
    split at h
    · exact .inl ⟨_, _, h⟩
    · split at h
      · rename_i hc
        simp only [Bool.or_eq_true] at hc
        exact .inr ⟨hc, h.symm⟩
      · exact .inl ⟨_, _, h⟩

/-- Every boundary a run sets stands where no turn of the person's was owed, on their acceptance or
    on nothing awaiting them, closed at the context where it was read — provided the outcome the run
    starts from (`ho`), where it is a boundary that stands, stood on those same grounds. This pins
    the grounds, not which context: that a step's boundary is read at the person's utterance is
    `defined_ends_in_utterance`. -/
theorem defined_by_acceptance_or_nothing_awaiting (c : Context P) (o : Outcome P)
    (us : List (Utterance P)) (b : DefinedBoundary P) (h : bound respond session c o us = .defined b)
    (ho : ∀ b', o = .defined b' → ∃ c₀ s₀, owed c₀ = false ∧
      (isFilled (acceptance c₀) = true ∨ awaits (readout c₀) = false) ∧
      b' = closeAt c₀ s₀ (readout c₀)) :
    ∃ c₀ s₀, owed c₀ = false ∧
      (isFilled (acceptance c₀) = true ∨ awaits (readout c₀) = false) ∧
      b = closeAt c₀ s₀ (readout c₀) := by
  induction us generalizing c o with
  | nil => cases o <;> simp [bound] at h; exact ho b (by rw [h])
  | cons u us ih =>
    cases o with
    | withdrawn w => simp [bound] at h
    | _ =>
      simp only [bound] at h
      split at h
      · refine ih _ _ h ?_
        intro b' hb'
        refine ho b' ?_
        simp only [Outcome.carry] at hb'
        first | exact hb' | cases hb'
      · split at h
        · cases h
        · refine ih _ _ h ?_
          intro b' hb'
          obtain ⟨h1, h2, h3⟩ := defined_grounds _ _ _ b' hb'
          exact ⟨_, _, h1, h2, h3⟩

/-- Every disposition on the record cites a person's turn: a relayed earlier decision — one fixing
    a decision's content or who settles it —, a fact, or a proposal of yours makes none. -/
theorem recorded_by_person (c : Context P) (r : Recorded c) : r.src.src.val = .person :=
  r.byPerson

/-- Where the person disposed a decision in this run, that disposition governs it — their current
    words — whatever an earlier decision fixed. -/
theorem current_disposition_governs {c : Context P} (e : BoundaryEntry c) (d : Disposition)
    (s : Cite c) (al : (dispositionOf (P := P) e.domain).admits s.src)
    (su : (dispositionOf (P := P) e.domain).supports c (c[s.idx]'s.lt) d)
    (hd : e.disposition = .filled d s al su) : governing e = some (d.arrangement, s) := by
  simp [governing, hd]

/-- Your choice inside a grant stands exactly where the arrangement governing the item entrusts the
    choice to you and the choice cites the turn that arrangement stands on. -/
theorem granted_choice_stands_iff {c : Context P} (e : BoundaryEntry c) (v : String)
    (src : Cite c) (allowed : (contentOf (P := P) e.domain).admits src.src)
    (supported : (contentOf (P := P) e.domain).supports c (c[src.idx]'src.lt)
      (.granted v))
    (hc : e.content = .filled (.granted v) src allowed supported) :
    stands e = true ↔
      ∃ a g, governing e = some (a, g) ∧ a.form = .aiAutonomous ∧ src.idx = g.idx := by
  cases hg : governing e with
  | none => simp [stands, hc, hg]
  | some p =>
    obtain ⟨a, g⟩ := p
    simp only [stands, hc, hg, Bool.and_eq_true, decide_eq_true_eq]
    constructor
    · intro h; exact ⟨a, g, rfl, h⟩
    · rintro ⟨a', g', he, h⟩
      cases he
      exact h

/-- Held content that stands — the person's own value, or one they took — stands on a person's
    turn; your choice inside a grant is its own form (`granted_choice_stands_iff`). -/
theorem held_content_cites_person {c : Context P} (e : BoundaryEntry c) (v : String)
    (p : Proposer) (st : Standing)
    (src : Cite c) (allowed : (contentOf (P := P) e.domain).admits src.src)
    (supported : (contentOf (P := P) e.domain).supports c (c[src.idx]'src.lt) (.held v p st))
    (hc : e.content = .filled (.held v p st) src allowed supported)
    (hs : stands e = true) : src.src.val = .person := by
  simpa [stands, hc] using hs

/-- Your choice inside a grant that an earlier decision fixing who settles the item states stands,
    citing that decision's record, where no disposition of this run governs the item and the
    earlier decision entrusts the choice to you: it is on the record as yours. -/
theorem granted_choice_under_prior_stands {c : Context P} (e : BoundaryEntry c) (v : String)
    (src : Cite c) (allowed : (contentOf (P := P) e.domain).admits src.src)
    (supported : (contentOf (P := P) e.domain).supports c (c[src.idx]'src.lt)
      (.granted v))
    (hc : e.content = .filled (.granted v) src allowed supported)
    (x : Option (Cite c)) (hd : e.disposition = .open_ x)
    (a : Arrangement) (ha : a.form = .aiAutonomous) (prior : Cite c)
    (al : (priorDispositionOf (P := P) e.domain).admits prior.src)
    (su : (priorDispositionOf (P := P) e.domain).supports c (c[prior.idx]'prior.lt) a)
    (hp : e.priorDisposition = .filled a prior al su) (hi : src.idx = prior.idx) :
    stands e = true := by
  simp [stands, hc, hd, hp, governing, ha, hi]

/-- Where the person's disposition in this run keeps a decision for themselves or for their
    selection, your choice inside an earlier decision's grant does not stand: their current words
    govern. -/
theorem override_blocks_prior_grant {c : Context P} (e : BoundaryEntry c) (v : String)
    (src : Cite c) (allowed : (contentOf (P := P) e.domain).admits src.src)
    (supported : (contentOf (P := P) e.domain).supports c (c[src.idx]'src.lt)
      (.granted v))
    (hc : e.content = .filled (.granted v) src allowed supported)
    (d : Disposition) (hf : d.arrangement.form ≠ .aiAutonomous) (s : Cite c)
    (al : (dispositionOf (P := P) e.domain).admits s.src)
    (su : (dispositionOf (P := P) e.domain).supports c (c[s.idx]'s.lt) d)
    (hd : e.disposition = .filled d s al su) : stands e = false := by
  simp [stands, hc, hd, governing, hf]

private theorem mem_residualOf {c : Context P} (m : BoundaryMap c) (e : BoundaryEntry c)
    (hm : e ∈ m) (hs : stands e = false) : openItemOf e ∈ residualOf m := by
  simp only [residualOf, List.mem_map, List.mem_filter]
  exact ⟨e, ⟨hm, by simp [hs]⟩, rfl⟩

/-- Every item on the map whose content does not stand is in the residual of the snapshot, with
    its question, why it bears, and the arrangement governing it — none where no disposition
    governs it yet. -/
theorem open_decisions_in_residual (c : Context P) (e : BoundaryEntry c)
    (hm : e ∈ (readout c).map) (hs : stands e = false) :
    openItemOf e ∈ (snapshotOf c).residual :=
  mem_residualOf _ e hm hs

/-- An item awaiting the person is in the residual, marked as governed by no arrangement yet. -/
theorem awaiting_in_residual (c : Context P) (e : BoundaryEntry c) (hm : e ∈ (readout c).map)
    (ha : awaitsEntry e = true) :
    openItemOf e ∈ (snapshotOf c).residual ∧ (openItemOf e).governing = none := by
  simp only [awaitsEntry, Bool.and_eq_true, Bool.not_eq_true', Option.isNone_iff_eq_none] at ha
  exact ⟨open_decisions_in_residual c e hm ha.2, by simp [openItemOf, ha.1]⟩

/-- An item whose disposition an earlier decision fixes does not await the person: it is shown
    with that citation and not asked again. -/
theorem prior_disposition_not_awaiting {c : Context P} (e : BoundaryEntry c)
    (h : isFilled e.priorDisposition = true) : awaitsEntry e = false := by
  cases hp : e.priorDisposition with
  | open_ _ => simp [hp, isFilled] at h
  | filled a s al su =>
    cases hd : e.disposition <;> simp [awaitsEntry, governing, hd, hp]

/-- A person's turn in this context never stands as an earlier decision fixing who settles an
    item: that turn fills the disposition. -/
theorem prior_disposition_not_the_persons (d : Domain) (g : Grounding)
    (h : (priorDispositionOf (P := P) d).admits g) : g.val ≠ .person := h

/-- An earlier decision fixing who settles a decision makes no disposition of this run: the record
    reads only the person's disposition. -/
theorem prior_disposition_records_nothing {c : Context P} (e : BoundaryEntry c)
    (x : Occ (priorDispositionOf (P := P) e.domain) c) :
    recordOf { e with priorDisposition := x } = recordOf e := by
  cases e with
  | mk d q r ev dep app pr disp pd ct => cases disp <;> rfl

/-- The snapshot carries the map, the record, the residual, what the map did not look at, and the
    dissent read from the context it is taken in; a withdrawal carries it at the person's word,
    and a boundary where it stands carries the map read there with the limits and dissent of the
    turn that shows it. -/
theorem snapshot_carries (c c' : Context P) :
    (snapshotOf c).context = c ∧ (snapshotOf c).dissent = dissent c ∧
      (snapshotOf c).residual = residualOf (readout c).map ∧
      (snapshotOf c).limits = (readout c).limits ∧
      ((closeAt c c' (readout c)).snapshot.limits = (readout c').limits ∧
        (closeAt c c' (readout c)).snapshot.dissent = dissent c' ∧
        (closeAt c c' (readout c)).snapshot.map = (readout c).map) :=
  ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

end Horismos
