module

public import Contract.Horismos

/-! The theorems the /bound contract guarantees, each stated and proved here; `Contract.Horismos` is
    the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee the
    audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Horismos

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {c : Context P} : Nonempty (BoundaryEssence c) := ⟨⟨[], ""⟩⟩
instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

variable (respond session : Context P → Response P)

/-- Silence settles nothing: with no further utterance the run stands as it was — a holding gate
    keeps holding, a boundary that stands keeps standing. -/
theorem silence (c : Context P) (o : Outcome P) : bound respond session c o [] = o := by
  simp [bound]

/-- The run opens on its first round, standing as the invoking context, with what observation
    returned, leaves it. -/
theorem start_rounds_first (c : Context P) (us : List (Utterance P)) :
    start respond session c us =
      bound respond session (observed c ++ [(respond (observed c)).val]) (status (observed c)) us :=
  rfl

/-- An utterance that does not bear on the boundary adds no round and leaves the run as it stood. -/
theorem unrelated_keeps_the_run (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Reaches (fuse c u)) :
    bound respond session c o (u :: us) =
      bound respond session (fuse c u ++ [(session (fuse c u)).val]) o us := by
  simp [bound, h]

/-- A withdrawal ends the run with the snapshot at the person's word and sets no boundary. -/
theorem withdrawal_ends (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (hr : Reaches (fuse c u))
    (h : isFilled (withdrawal (fuse c u)) = true) :
    bound respond session c o (u :: us) = .withdrawn (snapshotOf (fuse c u)) := by
  simp [bound, hr, h]

/-- Any other utterance that bears on the boundary is read where it is said, with what observation
    returned — the run stands as that leaves it — and then answered by your turn; also after the
    boundary stood, so a later correction reopens it. -/
theorem bearing_utterance_rounds (c : Context P) (o : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (hr : Reaches (fuse c u))
    (hw : isFilled (withdrawal (fuse c u)) = false) :
    bound respond session c o (u :: us) =
      bound respond session (observed (fuse c u) ++ [(respond (observed (fuse c u))).val])
        (status (observed (fuse c u))) us := by
  simp [bound, hr, hw]

/-- The boundary stands on one of two grounds: the person's acceptance, or no item awaiting their
    disposition. -/
theorem defined_grounds (c : Context P) (b : DefinedBoundary P) (h : status c = .defined b) :
    (isFilled (acceptance c) = true ∨ awaits (readout c) = false) ∧ b = close c := by
  unfold status at h
  dsimp only at h
  split at h
  · rename_i hc
    cases h
    simp only [Bool.or_eq_true, Bool.not_eq_true'] at hc
    exact ⟨hc, rfl⟩
  · cases h

/-- What observation joins to a context is evidence: no turn of yours, and no person's turn. -/
theorem observed_adds_evidence (c : Context P) :
    ∃ ev : List (Turn P), observed c = c ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer := by
  refine ⟨(observe c).map (·.val), rfl, ?_⟩
  intro e he
  simp only [List.mem_map] at he
  obtain ⟨x, _, rfl⟩ := he
  exact x.property

/-- Wherever the boundary stands, it is read before your turn: the context it closes is the one
    read — at the person's utterance, or at the start the invoking context — with only what
    observation returned after it. -/
theorem defined_before_your_turn (c : Context P) (b : DefinedBoundary P)
    (h : status (observed c) = .defined b) :
    ∃ ev : List (Turn P), b.snapshot.context = c ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer := by
  obtain ⟨_, rfl⟩ := defined_grounds (observed c) b h
  exact observed_adds_evidence c

/-- Where a person's utterance sets the boundary, the boundary is read at that utterance: the
    context it closes is the person's turn followed only by what observation returned. -/
theorem defined_at_utterance (c : Context P) (u : Utterance P) (b : DefinedBoundary P)
    (h : status (observed (fuse c u)) = .defined b) :
    ∃ ev : List (Turn P), b.snapshot.context = c ++ [u.val] ++ ev ∧
      ∀ e ∈ ev, e.origin = .external ∨ e.origin = .peer :=
  defined_before_your_turn (fuse c u) b h

/-- An acceptance sets the boundary whatever is still open; the open part is its residual. -/
theorem acceptance_sets_despite_residual (c : Context P) (h : isFilled (acceptance c) = true) :
    status c = .defined (close c) := by
  simp [status, close, snapshotOf, h]

/-- Where something awaits the person and they have not accepted, the gate holds. -/
theorem awaiting_holds (c : Context P) (ha : isFilled (acceptance c) = false)
    (hw : awaits (readout c) = true) : status c = .holding c := by
  simp [status, ha, hw]

theorem each_step_continues_or_withdraws (c : Context P) (o r : Outcome P) (u : Utterance P)
    (us : List (Utterance P)) (h : bound respond session c o (u :: us) = r) :
    (∃ c' o', bound respond session c' o' us = r) ∨
    (isFilled (withdrawal (fuse c u)) = true ∧ r = .withdrawn (snapshotOf (fuse c u))) := by
  simp only [bound] at h
  split at h
  · exact .inl ⟨_, _, h⟩
  · split at h
    · exact .inr ⟨by assumption, h.symm⟩
    · exact .inl ⟨_, _, h⟩

/-- A withdrawn run was withdrawn by the person's turn. -/
theorem withdrawn_by_person (c : Context P) (o : Outcome P) (us : List (Utterance P))
    (p : Snapshot P) (h : bound respond session c o us = .withdrawn p)
    (ho : ∀ q, o ≠ .withdrawn q) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ p = snapshotOf c₀ := by
  induction us generalizing c o with
  | nil => simp [bound] at h; exact absurd h (ho p)
  | cons u us ih =>
    simp only [bound] at h
    split at h
    · exact ih _ o h ho
    · split at h
      · cases h; exact ⟨_, by assumption, rfl⟩
      · refine ih _ _ h ?_
        intro q hq
        unfold status at hq
        dsimp only at hq
        split at hq <;> cases hq

/-- Every boundary a run sets, from a start that has not withdrawn, stands on the acceptance or on
    nothing awaiting the person, in the context where it was read. -/
theorem defined_by_acceptance_or_nothing_awaiting (c : Context P) (o : Outcome P)
    (us : List (Utterance P)) (b : DefinedBoundary P) (h : bound respond session c o us = .defined b)
    (ho : ∀ b', o = .defined b' → ∃ c₀, (isFilled (acceptance c₀) = true ∨
      awaits (readout c₀) = false) ∧ b' = close c₀) :
    ∃ c₀, (isFilled (acceptance c₀) = true ∨ awaits (readout c₀) = false) ∧ b = close c₀ := by
  induction us generalizing c o with
  | nil => simp [bound] at h; exact ho b h
  | cons u us ih =>
    simp only [bound] at h
    split at h
    · exact ih _ o h ho
    · split at h
      · cases h
      · refine ih _ _ h ?_
        intro b' hb'
        exact ⟨_, defined_grounds _ b' hb'⟩

/-- Every disposition on the record cites a person's turn: a relayed earlier decision — one fixing
    a decision's content or who settles it —, a fact, or a proposal of yours makes none. -/
theorem recorded_by_person (c : Context P) (r : Recorded c) : r.src.src.val = .person :=
  r.byPerson

/-- A disposition is never granted: only the person disposes. -/
theorem disposition_not_granted (d : Disposition) : d.standing ≠ .granted := d.notGranted

/-- Held content that stands — the person's own value, one they took, or your choice inside their
    grant — stands on a person's turn. -/
theorem held_content_cites_person {d : Domain} {c : Context P} (s : Settled) (src : Cite c)
    (allowed : (contentOf (P := P) d).admits src.src)
    (supported : (contentOf (P := P) d).supports c (c[src.idx]'src.lt) s)
    (hh : s.isHeld = true) (hs : stands (Occ.filled s src allowed supported) = true) :
    src.src.val = .person := by
  simp [stands, hh] at hs
  exact hs

private theorem mem_residualOf {c : Context P} (m : BoundaryMap c) (e : BoundaryEntry c)
    (hm : e ∈ m) (hs : stands e.content = false) : (e.domain, e.question) ∈ residualOf m := by
  simp only [residualOf, List.mem_map, List.mem_filter]
  exact ⟨e, ⟨hm, by simp [hs]⟩, rfl⟩

/-- Every item on the map whose content does not stand is in the residual of the boundary. -/
theorem open_decisions_in_residual (c : Context P) (e : BoundaryEntry c)
    (hm : e ∈ (readout c).map) (hs : stands e.content = false) :
    (e.domain, e.question) ∈ (close c).snapshot.residual :=
  mem_residualOf _ e hm hs

/-- An item awaiting the person is in the residual. -/
theorem awaiting_in_residual (c : Context P) (e : BoundaryEntry c) (hm : e ∈ (readout c).map)
    (ha : awaitsEntry e = true) : (e.domain, e.question) ∈ (close c).snapshot.residual := by
  apply open_decisions_in_residual c e hm
  simp only [awaitsEntry, Bool.and_eq_true, Bool.not_eq_true'] at ha
  exact ha.2

/-- An item whose disposition an earlier decision fixes does not await the person: it is shown
    with that citation and not asked again. -/
theorem prior_disposition_not_awaiting {c : Context P} (e : BoundaryEntry c)
    (h : isFilled e.priorDisposition = true) : awaitsEntry e = false := by
  simp [awaitsEntry, h]

/-- A person's turn in this context never stands as an earlier decision fixing who settles an
    item: that turn fills the disposition. -/
theorem prior_disposition_not_the_persons (d : Domain) (g : Grounding)
    (h : (priorDispositionOf (P := P) d).admits g) : g.val ≠ .person := h

/-- An earlier decision fixing who settles a decision makes no disposition of this run: the record
    reads only the person's disposition. -/
theorem prior_disposition_records_nothing {c : Context P} (e : BoundaryEntry c)
    (x : Occ (priorDispositionOf (P := P) e.domain) c) :
    recordOf { e with priorDisposition := x } = recordOf e := by
  cases e with
  | mk d q r ev dep app pr disp pd ct => cases disp <;> rfl

/-- The snapshot carries the map, the record, the residual, what the map did not look at, and the
    dissent read from the context it is taken in; the boundary and a withdrawal carry the same. -/
theorem snapshot_carries (c : Context P) :
    (snapshotOf c).context = c ∧ (snapshotOf c).dissent = dissent c ∧
      (snapshotOf c).residual = residualOf (readout c).map ∧
      (snapshotOf c).limits = (readout c).limits ∧ (close c).snapshot = snapshotOf c :=
  ⟨rfl, rfl, rfl, rfl, rfl⟩

end Horismos
