module

public import Contract.Hypotyposis
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /sketch SKILL.md Lean block states; `Contract.Hypotyposis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Hypotyposis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Verdict := ⟨.cont⟩

theorem silence (relay respond : Context P → Response P) (c : Context P) :
    sketch relay respond c [] = .holding c := by
  simp [sketch]

theorem relay_before_production (relay : Context P → Response P) (c : Context P) :
    ∃ t, runRound relay c = c ++ [(relay c).val] ++ t :=
  ⟨_, rfl⟩

theorem held_gate_produces_nothing (relay respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hv : verdict (fuse c u) = .cont)
    (hb : ¬ AIBoundary (fuse c u)) (hh : Placing (fuse c u) ∨ ¬ Redraws (fuse c u)) :
    sketch relay respond c (u :: us) =
      sketch relay respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [sketch, hv, hb, hh]

theorem unverified_returns_to_placement (relay respond : Context P → Response P)
    (c : Context P) (u : Utterance P) (us : List (Utterance P)) (f : Fixture)
    (hv : verdict (fuse c u) = .place) (hf : fixture (settle (fuse c u)) = some f)
    (hn : ¬ Verified (settle (fuse c u)) f) :
    sketch relay respond c (u :: us) =
      sketch relay respond (settle (fuse c u) ++ [(respond (settle (fuse c u))).val]) us := by
  simp [sketch, hv, hf, hn]

theorem recognized_verified (relay respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : RecognizedForm P)
    (h : sketch relay respond c us = .recognized r) :
    ∃ c₁, Verified c₁ r.fixture ∧ r = recognize c₁ r.fixture := by
  induction us generalizing c with
  | nil => simp [sketch] at h
  | cons u us ih =>
    simp only [sketch] at h
    split at h
    · cases h
    · cases h
    · cases h
    · split at h
      · rename_i f _
        split at h
        · rename_i hver
          cases h
          exact ⟨_, hver, rfl⟩
        · exact ih _ h
      · exact ih _ h
    · split at h
      · cases h
      · split at h
        · exact ih _ h
        · exact ih _ h

theorem dissolved_by_person (relay respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Closing P) (h : sketch relay respond c us = .dissolved r) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .dissolve ∧ r = closing (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [sketch] at h
  | cons u us ih =>
    simp only [sketch] at h
    split at h
    · cases h
    · rename_i hd
      cases h
      exact ⟨c, u, hd, rfl⟩
    · cases h
    · split at h
      · split at h
        · cases h
        · exact ih _ h
      · exact ih _ h
    · split at h
      · cases h
      · split at h
        · exact ih _ h
        · exact ih _ h

theorem settled_by_utterance {c : Context P} {a : Axis} {s : Cite c}
    (ok : (axisCoord (P := P) a).admits s.src) : s.src.val = .person := ok

theorem recognized_by_utterance {c : Context P} {s : Cite c}
    (ok : (recognitionCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem placed_by_utterance {c : Context P} {s : Cite c}
    (ok : (placementCoord (P := P)).admits s.src) : s.src.val = .person := ok

end Hypotyposis
