module

public import Contract.Heuresis

/-! Proofs of the theorems the /ideate SKILL.md Lean block states; `Contract.Heuresis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Heuresis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance : Nonempty Entry := ⟨.blank⟩
instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (generate respond : Context P → Response P) (c : Context P) :
    ideate generate respond c [] = .holding c := by
  simp [ideate]

theorem blank_frame_map_first (relay generate respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P))
    (h : entry (c ++ (reference c).map (·.val) ++ [(relay (c ++ (reference c).map (·.val))).val])
      = .blank) :
    start relay generate respond c us =
      ideate generate respond
        (c ++ (reference c).map (·.val) ++ [(relay (c ++ (reference c).map (·.val))).val] ++
          [(respond (c ++ (reference c).map (·.val) ++
            [(relay (c ++ (reference c).map (·.val))).val])).val]) us := by
  simp only [start, h]

theorem no_empty_pass (generate respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hk : filledValue (closing (fuse c u)) = none)
    (ht : (targets (fuse c u)).isEmpty = true) :
    ideate generate respond c (u :: us) =
      ideate generate respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [ideate, hk, ht]

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem parked_by_person (c : Context P) (p : ParkedFollowUp c) :
    (c[p.request.idx]'p.request.lt).origin = .person :=
  p.request.ok.trans p.byPerson

theorem explored_registered {c : Context P} {f : Frame} (h : f ∈ explored c) : f ∈ frames c :=
  (List.mem_filter.mp h).1

theorem explored_not_unexplored {c : Context P} {f : Frame} (h : f ∈ explored c) :
    ¬ Unexplored c f := by
  intro hu
  have := (List.mem_filter.mp h).2
  simp [hu.2] at this

theorem field_has_candidates (r : DiverseCandidateField P) : candidates r.context ≠ [] := by
  intro h
  have := r.nonempty
  simp [h] at this

theorem early_all_unaddressed (r : EarlyExit P) (s : Signal) (hs : s ∈ signals r.context) :
    Unaddressed r.context s := by
  have he : candidates r.context = [] := List.isEmpty_iff.mp r.empty
  refine ⟨hs, ?_⟩
  rintro ⟨x, hx, _⟩
  simp [he] at hx

end Heuresis
