module

public import Contract.Heuresis

/-! Proofs of the theorems the /ideate SKILL.md Lean block states; `Contract.Heuresis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Heuresis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance : Nonempty ExpansionWitness := ⟨.empty⟩
instance : Nonempty Entry := ⟨.blank⟩
instance : Nonempty Verdict := ⟨.stop⟩

theorem silence (generate respond : Context P → Response P) (c : Context P) :
    ideate generate respond c [] = .holding c := by
  simp [ideate]

theorem blank_frame_map_first (relay generate respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (h : entry (c ++ [(relay c).val]) = .blank) :
    start relay generate respond c us =
      ideate generate respond (c ++ [(relay c).val] ++ [(respond (c ++ [(relay c).val])).val]) us := by
  simp only [start, h]

theorem no_empty_pass (generate respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hv : verdict (fuse c u) = .cont)
    (ht : (targets (fuse c u)).isEmpty = true) :
    ideate generate respond c (u :: us) =
      ideate generate respond (fuse c u ++ [(respond (fuse c u)).val]) us := by
  simp [ideate, hv, ht]

theorem stop_assembles (generate respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hv : verdict (fuse c u) = .stop) :
    ideate generate respond c (u :: us) = assemble (fuse c u) := by
  simp [ideate, hv]

theorem field_by_person (generate respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : DiverseCandidateField P)
    (h : ideate generate respond c us = .field r) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .stop ∧ r.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [ideate] at h
  | cons u us ih =>
    simp only [ideate] at h
    split at h
    · rename_i hv
      unfold assemble at h
      split at h
      · cases h
      · cases h
        exact ⟨c, u, hv, rfl⟩
    · split at h
      · exact ih _ h
      · exact ih _ h

theorem early_by_person (generate respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : EarlyExit P)
    (h : ideate generate respond c us = .early r) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .stop ∧ r.context = fuse c₀ u := by
  induction us generalizing c with
  | nil => simp [ideate] at h
  | cons u us ih =>
    simp only [ideate] at h
    split at h
    · rename_i hv
      unfold assemble at h
      split at h
      · cases h
        exact ⟨c, u, hv, rfl⟩
      · cases h
    · split at h
      · exact ih _ h
      · exact ih _ h

theorem field_has_candidates (r : DiverseCandidateField P) : candidates r.context ≠ [] := by
  intro h
  have := r.nonempty
  simp [h] at this

theorem early_all_unaddressed (r : EarlyExit P) (s : Signal) (hs : s ∈ signals r.context) :
    Unaddressed r.context s := by
  have he : candidates r.context = [] := List.isEmpty_iff.mp r.empty
  refine ⟨hs, ?_⟩
  rintro ⟨x, hx, _⟩
  simp [he] at hx

theorem explored_not_unexplored {c : Context P} {f : Frame} (h : Unexplored c f) :
    f ∉ opened c :=
  h.2

end Heuresis
