module

public import Contract.Heuresis

/-! The theorems the /ideate contract has. `Contract.Heuresis` is the SKILL.md Lean block,
    generated by lean-contract.js; `Proofs.lean` proves each theorem stated here, and the
    lean-definition check re-derives every statement from the proved theorem of its name. The
    runtime surface carries only what the model reads, so the statements live here. -/

namespace Heuresis

variable {P : Type}

/-!
Silence assembles nothing.
theorem silence (generate respond : Context P → Response P) (c : Context P) :
    ideate generate respond c [] = .holding c

On a Blank entry the frame map comes before any candidate.
theorem blank_frame_map_first (relay generate respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P))
    (h : entry (c ++ (reference c).map (·.val) ++ [(relay (c ++ (reference c).map (·.val))).val])
      = .blank) :
    start relay generate respond c us =
      ideate generate respond
        (c ++ (reference c).map (·.val) ++ [(relay (c ++ (reference c).map (·.val))).val] ++
          [(respond (c ++ (reference c).map (·.val) ++
            [(relay (c ++ (reference c).map (·.val))).val])).val]) us

An answer that closes nothing and opens nothing runs no pass: the gate is presented again.
theorem no_empty_pass (generate respond : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hk : filledValue (closing (receive c u)) = none)
    (ht : (targets (receive c u)).isEmpty = true) :
    ideate generate respond c (u :: us) =
      ideate generate respond (receive c u ++ [(respond (receive c u)).val]) us

Every closing rests on a turn the person sent.
theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person

Every parked follow-up cites a turn the person sent.
theorem parked_by_person (c : Context P) (p : ParkedFollowUp c) :
    (c[p.request.idx]'p.request.lt).origin = .person

Every exclusion cites a turn the person sent.
theorem excluded_by_person (c : Context P) (e : Exclusion c) :
    (c[e.request.idx]'e.request.lt).origin = .person

No explored frame lies outside the register, and none is also unexplored.
theorem explored_registered {c : Context P} {f : Frame} (h : f ∈ explored c) : f ∈ frames c

theorem explored_not_unexplored {c : Context P} {f : Frame} (h : f ∈ explored c) :
    ¬ Unexplored c f

A field always carries a candidate.
theorem field_has_candidates (r : DiverseCandidateField P) : candidates r.context ≠ []

At an early exit every signal is unaddressed.
theorem early_all_unaddressed (r : EarlyExit P) (s : Signal) (hs : s ∈ signals r.context) :
    Unaddressed r.context s
-/

end Heuresis
