module

public import Contract.Katalepsis

/-! Proofs of the theorems the /grasp SKILL.md Lean block states; `Contract.Katalepsis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Katalepsis

variable {P : Type}

theorem silence (respond : Context P → Gate → Response P) (trace : Context P → Response P)
    (c : Context P) : grasp respond trace c [] = .holding c := by
  simp [grasp]

theorem horizon_preempts (c : Context P) (t : RecordId) (hd : HorizonDue c t) :
    gateFor c t = .horizonProbe t := by
  simp [gateFor, hd]

theorem horizon_preempts_return (c : Context P) (t : RecordId) (g : Gate)
    (hd : HorizonDue c t) : settle c t g = .horizonProbe t := by
  simp [settle, hd]

theorem asked_not_reasked (c : Context P) (t : RecordId) (hc : HorizonCandidate)
    (ha : admissible c t = some hc) (hk : Asked c t hc) : gateFor c t ≠ .horizonProbe t := by
  have hnd : ¬ HorizonDue c t := by
    rintro ⟨hc', ha', hk'⟩
    rw [ha] at ha'
    cases ha'
    exact hk' hk
  simp only [gateFor, hnd, ↓reduceIte]
  split
  · exact fun h => Gate.noConfusion h
  · split <;> exact fun h => Gate.noConfusion h

theorem miss_discloses (c : Context P) (t : RecordId) (hm : ¬ Reached c) (hs : ¬ AsksSteps c)
    (hi : otherIntent c = none) :
    advance c (.horizonProbe t) .cont = .gate (c ++ (attach c).map (·.val)) (.reveal t) := by
  simp [advance, horizonAnswer, hm, hs, hi]

theorem other_intent_no_disclosure (c : Context P) (t : RecordId) (e : EntryPoint)
    (hm : ¬ Reached c) (hs : ¬ AsksSteps c) (hi : otherIntent c = some e) :
    advance c (.horizonProbe t) .cont = .gate c (redirect c e) ∧ ∀ t', redirect c e ≠ .reveal t' := by
  refine ⟨by simp [advance, horizonAnswer, hm, hs, hi], ?_⟩
  intro t'
  unfold redirect
  split
  · unfold gateFor
    split
    · exact fun h => Gate.noConfusion h
    · split
      · exact fun h => Gate.noConfusion h
      · split <;> exact fun h => Gate.noConfusion h
  · exact fun h => Gate.noConfusion h

theorem probe_other_intent (c : Context P) (t : RecordId) (g : Selectable) (e : EntryPoint)
    (hi : otherIntent c = some e) : advance c (.probe t g) .cont = .gate c (redirect c e) := by
  simp [advance, hi]

theorem steps_cue (c : Context P) (t : RecordId) (hm : ¬ Reached c) (hs : AsksSteps c) :
    advance c (.horizonProbe t) .cont = .gate c (.cue t) := by
  simp [advance, horizonAnswer, hm, hs]

theorem choice_yields_to_horizon (c : Context P) (g : Gate) (t : RecordId)
    (hd : HorizonDue c t) : aspectStep c g t = .gate c (.horizonProbe t) := by
  unfold aspectStep
  split <;> simp [settle, hd]

theorem reached_taken (c : Context P) (t : RecordId) (hr : Reached c) :
    advance c (.horizonProbe t) .cont = .gate c (settle c t (.coverage t)) := by
  simp [advance, horizonAnswer, hr]

theorem no_adjudication_at_probe (c : Context P) (t : RecordId) (g : Selectable) :
    advance c (.probe t g) .cont = .gate c (.inquiry t g.val) ∨
      advance c (.probe t g) .cont = .gate c (settle c t (.coverage t)) ∨
      ∃ e, advance c (.probe t g) .cont = .gate c (redirect c e) := by
  cases hi : otherIntent c with
  | some e => exact Or.inr (Or.inr ⟨e, by simp [advance, hi]⟩)
  | none =>
    by_cases ho : Objection c
    · left; simp [advance, hi, ho]
    · right; left; simp [advance, hi, ho]

theorem advance_shape (c : Context P) (g : Gate) (v : Verdict) :
    (∃ c₁ g₁, advance c g v = .gate c₁ g₁) ∨
      (v = .complete ∧ ∃ t, advance c g v = .done (c ++ t)) ∨
      (v = .withdraw ∧ advance c g v = .withdrawn c) := by
  have hb : ∀ (c : Context P) (t : Task), ∃ c₁ g₁, beginTask c t = .gate c₁ g₁ :=
    fun _ _ => ⟨_, _, rfl⟩
  have ha : ∀ (c : Context P) (g : Gate) (t : RecordId),
      ∃ c₁ g₁, aspectStep c g t = .gate c₁ g₁ := by
    intro c g t
    unfold aspectStep
    split
    · exact ⟨_, _, rfl⟩
    · exact ⟨_, _, rfl⟩
  have hc : ∀ (c : Context P),
      (∃ t, completeStep c = .done (c ++ t)) ∨ ∃ c₁ g₁, completeStep c = .gate c₁ g₁ := by
    intro c
    simp only [completeStep]
    generalize current (c ++ (update c).map (·.val)) = o
    cases o with
    | none => exact Or.inl ⟨_, rfl⟩
    | some t => exact Or.inr (hb _ _)
  have hcomplete : ∀ (g : Gate), advance c g .complete = completeStep c →
      (∃ c₁ g₁, advance c g .complete = .gate c₁ g₁) ∨
        (Verdict.complete = .complete ∧ ∃ t, advance c g .complete = .done (c ++ t)) ∨
        (Verdict.complete = .withdraw ∧ advance c g .complete = .withdrawn c) := by
    intro g hg
    rw [hg]
    rcases hc c with ⟨t, ht⟩ | ⟨c₁, g₁, ht⟩
    · exact Or.inr (Or.inl ⟨rfl, t, ht⟩)
    · exact Or.inl ⟨c₁, g₁, ht⟩
  have hentry : ∀ (v : Verdict), v ≠ .propose → v ≠ .withdraw →
      ∃ c₁ g₁, advance c .entrySelection v = .gate c₁ g₁ := by
    intro v hp hw
    cases v with
    | propose => exact absurd rfl hp
    | withdraw => exact absurd rfl hw
    | cont =>
      simp only [advance]
      split
      · split
        · exact hb _ _
        · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
    | complete =>
      simp only [advance]
      split
      · split
        · exact hb _ _
        · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
  have hh : ∀ (t : RecordId), ∃ c₁ g₁, horizonAnswer c t = .gate c₁ g₁ := by
    intro t
    unfold horizonAnswer
    split
    · exact ⟨_, _, rfl⟩
    · split
      · exact ⟨_, _, rfl⟩
      · split
        · exact ⟨_, _, rfl⟩
        · exact ⟨_, _, rfl⟩
  cases v with
  | propose => exact Or.inl ⟨_, _, by cases g <;> rfl⟩
  | withdraw => exact Or.inr (Or.inr ⟨rfl, by cases g <;> rfl⟩)
  | complete =>
    cases g with
    | zeroGap t => exact hcomplete _ rfl
    | coverage t => exact hcomplete _ rfl
    | entrySelection => exact Or.inl (hentry _ (by simp) (by simp))
    | horizonProbe t => left; simp only [advance]; exact hh t
    | cue t => left; simp only [advance]; exact hh t
    | reveal t =>
      left; simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
    | startAspect t => exact Or.inl (ha c (.startAspect t) t)
    | probe t g =>
      left; simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · split
        · exact ⟨_, _, rfl⟩
        · exact ⟨_, _, rfl⟩
    | inquiry t g =>
      left; simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
  | cont =>
    left
    cases g with
    | entrySelection => exact hentry _ (by simp) (by simp)
    | zeroGap t => exact ⟨_, _, rfl⟩
    | horizonProbe t => simp only [advance]; exact hh t
    | cue t => simp only [advance]; exact hh t
    | reveal t =>
      simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
    | startAspect t => exact ha c (.startAspect t) t
    | probe t g =>
      simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · split
        · exact ⟨_, _, rfl⟩
        · exact ⟨_, _, rfl⟩
    | inquiry t g =>
      simp only [advance]; split
      · exact ⟨_, _, rfl⟩
      · exact ⟨_, _, rfl⟩
    | coverage t => exact ha c (.coverage t) t

theorem proposal_resumes (c : Context P) (g : Gate) :
    advance c g .propose = .gate (c ++ (eject c).map (·.val)) (resumeOf g) := by
  cases g <;> simp [advance]

theorem defeated_attaches_nothing (c : Context P) (t : RecordId) (g : GapType)
    (hs : ¬ Stands c) : advance c (.inquiry t g) .cont = .gate c (settle c t (.coverage t)) := by
  simp [advance, hs]

theorem verified_by_person (respond : Context P → Gate → Response P)
    (trace : Context P → Response P) (c : Context P) (us : List (Utterance P))
    (v : VerifiedUnderstanding P) (hv : grasp respond trace c us = .verified v) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .complete ∧
      ∃ t, v.context = fuse c₀ u ++ t := by
  induction us generalizing c with
  | nil => simp [grasp] at hv
  | cons u us ih =>
    simp only [grasp] at hv
    split at hv
    · rename_i c₁ hd
      rcases advance_shape (fuse c u) (answered c) (verdict (fuse c u)) with
        ⟨_, _, hg⟩ | ⟨hvc, t, ht⟩ | ⟨_, hw⟩
      · rw [hg] at hd; cases hd
      · rw [ht] at hd
        cases hd
        cases hv
        exact ⟨c, u, hvc, t ++ [(trace (fuse c u ++ t)).val], by simp [understanding]⟩
      · rw [hw] at hd; cases hd
    · cases hv
    · exact ih _ hv

theorem withdrawn_by_person (respond : Context P → Gate → Response P)
    (trace : Context P → Response P) (c : Context P) (us : List (Utterance P))
    (c₁ : Context P) (d : List String) (hw : grasp respond trace c us = .withdrawn c₁ d) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .withdraw ∧
      ∃ t, c₁ = fuse c₀ u ++ t := by
  induction us generalizing c with
  | nil => simp [grasp] at hw
  | cons u us ih =>
    simp only [grasp] at hw
    split at hw
    · cases hw
    · rename_i c₂ hd
      rcases advance_shape (fuse c u) (answered c) (verdict (fuse c u)) with
        ⟨_, _, hg⟩ | ⟨_, t, ht⟩ | ⟨hvw, hx⟩
      · rw [hg] at hd; cases hd
      · rw [ht] at hd; cases hd
      · rw [hx] at hd
        cases hd
        cases hw
        exact ⟨c, u, hvw, [(trace (fuse c u)).val], rfl⟩
    · exact ih _ hw

theorem completed_by_utterance {c : Context P} {t : RecordId} {s : Cite c}
    (ok : (completionCoord (P := P) t).admits s.kind) : s.kind = .utterance := ok

theorem selected_by_utterance {c : Context P} {s : Cite c}
    (ok : (selectionCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem aspect_by_utterance {c : Context P} {s : Cite c}
    (ok : (aspectCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem selectable_not_horizon (g : Selectable) : g.val ≠ .horizon := g.property

end Katalepsis
