module

public import Contract.Katalepsis

/-! Proofs of the theorems the /grasp SKILL.md Lean block states; `Contract.Katalepsis` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Katalepsis

variable {P : Type}

theorem silence (respond : Context P → Gate → Response P) (c : Context P) (h : Horizon) :
    grasp respond c h [] = .holding c := by
  simp [grasp]

theorem horizon_preempts (c : Context P) (h : Horizon) (t : RecordId)
    (hd : t ∈ h.detected) (hp : t ∉ h.probed) :
    gateFor c h t = .horizonProbe t := by
  simp [gateFor, hd, hp]

theorem horizon_once (c : Context P) (h : Horizon) (t : RecordId)
    (hg : gateFor c h t = .horizonProbe t) : t ∉ h.probed := by
  unfold gateFor at hg
  split at hg
  · rename_i hc
    exact hc.2
  · split at hg
    · cases hg
    · split at hg <;> cases hg

theorem horizon_taken (c : Context P) (h : Horizon) (t : RecordId) :
    advance c h (.horizonProbe t) .cont = .gate c h (.coverage t) := by
  simp [advance]

theorem no_adjudication_at_probe (c : Context P) (h : Horizon) (t : RecordId) (g : Selectable) :
    advance c h (.probe t g) .cont = .gate c h (.inquiry t g) ∨
      advance c h (.probe t g) .cont = .gate c h (.coverage t) := by
  by_cases ho : Objection c
  · left; simp [advance, ho]
  · right; simp [advance, ho]

theorem proposal_resumes (c : Context P) (h : Horizon) (g : Gate) :
    advance c h g .propose = .gate (c ++ (eject c).map (·.val)) h (resumeOf g) := by
  cases g <;> simp [advance]

theorem verified_by_person (respond : Context P → Gate → Response P) (c : Context P)
    (h : Horizon) (us : List (Utterance P)) (v : VerifiedUnderstanding P)
    (hv : grasp respond c h us = .verified v) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .complete ∧
      ∃ t, v.context = fuse c₀ u ++ t := by
  have beginTask_gate : ∀ (c : Context P) (h : Horizon) (t : Task) (c₁ : Context P),
      beginTask c h t ≠ .done c₁ := by
    intro c h t c₁; simp [beginTask]
  have aspectStep_gate : ∀ (c : Context P) (h : Horizon) (g : Gate) (t : RecordId)
      (c₁ : Context P), aspectStep c h g t ≠ .done c₁ := by
    intro c h g t c₁; unfold aspectStep; split <;> simp
  have completeStep_done : ∀ (c : Context P) (h : Horizon) (c₁ : Context P),
      completeStep c h = .done c₁ → ∃ t, c₁ = c ++ t := by
    intro c h c₁ hd
    simp only [completeStep] at hd
    generalize current (c ++ (update c).map (·.val)) = o at hd
    cases o with
    | none => cases hd; exact ⟨_, rfl⟩
    | some t => exact absurd hd (beginTask_gate _ _ _ _)
  have advance_done : ∀ (c : Context P) (h : Horizon) (g : Gate) (v : Verdict)
      (c₁ : Context P), advance c h g v = .done c₁ → v = .complete ∧ ∃ t, c₁ = c ++ t := by
    intro c h g v c₁ hd
    cases v with
    | propose => cases g <;> simp [advance] at hd
    | complete =>
      refine ⟨rfl, ?_⟩
      cases g with
      | zeroGap t => exact completeStep_done c h c₁ (by simpa [advance] using hd)
      | coverage t => exact completeStep_done c h c₁ (by simpa [advance] using hd)
      | entrySelection =>
        simp only [advance] at hd
        split at hd
        · split at hd
          · exact absurd hd (beginTask_gate _ _ _ _)
          · cases hd
        · cases hd
      | horizonProbe t => simp [advance] at hd
      | startAspect t => exact absurd (by simpa [advance] using hd) (aspectStep_gate _ _ _ _ _)
      | probe t g => simp only [advance] at hd; split at hd <;> cases hd
      | inquiry t g => simp only [advance] at hd; split at hd <;> cases hd
    | cont =>
      exfalso
      cases g with
      | entrySelection =>
        simp only [advance] at hd
        split at hd
        · split at hd
          · exact beginTask_gate _ _ _ _ hd
          · cases hd
        · cases hd
      | zeroGap t => simp [advance] at hd
      | horizonProbe t => simp [advance] at hd
      | startAspect t => exact aspectStep_gate _ _ _ _ _ (by simpa [advance] using hd)
      | probe t g => simp only [advance] at hd; split at hd <;> cases hd
      | inquiry t g => simp only [advance] at hd; split at hd <;> cases hd
      | coverage t => exact aspectStep_gate _ _ _ _ _ (by simpa [advance] using hd)
  induction us generalizing c h with
  | nil => simp [grasp] at hv
  | cons u us ih =>
    simp only [grasp] at hv
    split at hv
    · rename_i c₁ hd
      obtain ⟨hvc, t, rfl⟩ := advance_done _ _ _ _ _ hd
      cases hv
      exact ⟨c, u, hvc, t, rfl⟩
    · exact ih _ _ hv

theorem completed_by_utterance {c : Context P} {t : RecordId} {s : Cite c}
    (ok : (completionCoord (P := P) t).admits s.kind) : s.kind = .utterance := ok

theorem selected_by_utterance {c : Context P} {s : Cite c}
    (ok : (selectionCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem aspect_by_utterance {c : Context P} {s : Cite c}
    (ok : (aspectCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem selectable_not_horizon (g : Selectable) : g.val ≠ .horizon := g.property

end Katalepsis
