module

public import Contract.Katalepsis

/-! The theorems the /grasp contract has. `Contract.Katalepsis` is the SKILL.md Lean block,
    generated by lean-contract.js; `Proofs.lean` proves each theorem stated here, and the
    lean-definition check re-derives every statement from the proved theorem of its name. The
    runtime surface carries only what the model reads, so the statements live here. -/

namespace Katalepsis

variable {P : Type}

/-!
The transition, history, grounding and convergence laws.
theorem earlier_turns_never_reread (c t : Context P) : ∃ more, said (c ++ t) = said c ++ more

theorem responses_say_nothing (c : Context P) (r : Response P) : said (c ++ [r.val]) = said c

theorem said_by_person (c : Context P) (i : Nat) (x : Record) (h : (i, x) ∈ said c) :
    ∃ u : Utterance P, c[i]? = some u.val

theorem silence (respond : (c : Context P) → Round c → Response P)
    (trace : Context P → Trace → Response P) (c : Context P) :
    grasp respond trace c [] = .holding c

theorem user_conflict_first (c : Context P) (t : RecordId) (g : Gate)
    (k : Contradiction c) (h : userConflict c t = some k) :
    (settle c t g).gate = .conflict t

theorem horizon_preempts (c : Context P) (t : RecordId) (g : Gate)
    (hu : userConflict c t = none) (h : HorizonCandidate)
    (hd : dueHorizon c t = some h) :
    (settle c t g).gate = .horizonProbe t h.edge

theorem asked_not_due (c : Context P) (t : RecordId) (h : HorizonCandidate)
    (ha : admissible (assess c t) = some h) (hk : Asked c t h.edge) :
    dueHorizon c t = none

theorem singleton_admission (a : Assessment (P := P) c) (h : HorizonCandidate)
    (ha : admissible a = some h) : a.candidates = [h]

theorem miss_discloses_material (c : Context P) (t : RecordId) (edge : String)
    (a : Adjudication c) :
    advance c ⟨.horizonProbe t edge, .correct a⟩ = .gate ⟨.reveal t edge, [.material a]⟩

theorem conflict_resolves_material (c : Context P) (t : RecordId) (a : Adjudication c) :
    advance c ⟨.conflict t, .correct a⟩ = .gate ⟨.resolve t, [.material a]⟩

theorem inquiry_corrects_material (c : Context P) (t : RecordId) (g : Aspect)
    (a : Adjudication c) :
    advance c ⟨.inquiry t g, .correct a⟩ = .gate ⟨again t g, [.material a]⟩

theorem other_intent_redirects (c : Context P) (g : Gate) (e : EntryPoint) (basis : String) :
    advance c ⟨g, .other e basis⟩ = .gate (redirect c e basis)

theorem steps_cue (c : Context P) (t : RecordId) (edge : String) :
    advance c ⟨.horizonProbe t edge, .steps⟩ = .gate ⟨.cue t edge, []⟩

theorem proposal_recorded (c : Context P) (g : Gate) (s : String) :
    advance c ⟨g, .propose s⟩ = .gate ⟨resumeOf g, [.proposal s]⟩

theorem no_verdict_without_measure (c : Context P) (g : Gate) (why : String) :
    advance c ⟨g, .accepted why⟩ = .gate (returning c g why)

theorem no_adjudication_at_probe (c : Context P) (t : RecordId) (g : Selectable)
    (a : Adjudication c) :
    advance c ⟨.probe t g, .correct a⟩ = .gate ⟨.probe t g, []⟩

theorem completed_persists (c more : Context P) (t : RecordId) (h : completed c t) :
    completed (c ++ more) t

theorem tasks_persist (c more : Context P) : ∃ ts, tasks (c ++ more) = tasks c ++ ts

theorem certified_nonempty (v : VerifiedUnderstanding P) : tasks v.basis ≠ []

theorem certified_all_closed (v : VerifiedUnderstanding P) :
    ∀ t ∈ tasks v.basis, completed v.basis t.id

theorem completed_by_person (c : Context P) (t : RecordId) (h : completed c t) :
    ∃ i r, ∃ u : Utterance P, c[i]? = some u.val ∧ (i, r) ∈ said c ∧
      r.gate.task = some t ∧ r.act = .close

theorem advance_done_closed (c : Context P) (r : Reading c) (h : AllClosed c)
    (hd : advance c r = .done h) : (recorded r).act = .close

theorem advance_withdrawn (c : Context P) (r : Reading c)
    (h : advance c r = .withdrawn) : r.answer = .withdraw

theorem verified_by_person (respond : (c : Context P) → Round c → Response P)
    (trace : Context P → Trace → Response P) (c : Context P) (us : List (Utterance P))
    (v : VerifiedUnderstanding P) (hv : grasp respond trace c us = .verified v) :
    ∃ (c₀ : Context P) (u : Utterance P), v.basis = consulted c₀ u ∧
      (recorded (read c₀ u)).act = .close ∧ AllClosed v.basis

theorem withdrawn_by_person (respond : (c : Context P) → Round c → Response P)
    (trace : Context P → Trace → Response P) (c : Context P) (us : List (Utterance P))
    (basis : Context P) (presentation : Response P)
    (hw : grasp respond trace c us = .withdrawn basis presentation) :
    ∃ (c₀ : Context P) (u : Utterance P), basis = consulted c₀ u ∧ (read c₀ u).answer = .withdraw

theorem selection_never_horizon (g : Selectable) : g.val ≠ .horizon

theorem selection_never_conflict (g : Selectable) : g.val ≠ .contradiction

theorem close_at_closing_gate (c : Context P) (r : Reading c)
    (h : (recorded r).act = .close) : r.gate.closable = true ∧ r.answer = .choose .close

theorem shown_requires_measure (c : Context P) (r : Reading c)
    (h : (recorded r).act = .met) : ∃ m, r.answer = .met m

theorem disclosure_stays_assisted (c : Context P) (t : RecordId) (g : Aspect)
    (h : (said c).any (fun (_, r) => r.gate.task == some t && r.gate.aspect == some g &&
      match r.act with | .correct => true | _ => false) = true) :
    assistance c t g = .afterDisclosure

theorem other_intent_no_disclosure (c : Context P) (e : EntryPoint) (basis : String)
    (t : RecordId) (edge : String) :
    (redirect c e basis).gate ≠ .reveal t edge ∧ (redirect c e basis).gate ≠ .resolve t
-/

end Katalepsis
