module

public import Contract.Katalepsis

/-! The theorems the /grasp contract guarantees, each stated and proved here; `Contract.Katalepsis`
    is the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee
    the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Katalepsis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond session : Context P → Response P) (c : Context P) :
    grasp respond session c [] = .holding c := by
  simp [grasp]

theorem start_presents_first (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) :
    start respond session c us =
      grasp respond session (consulted c ++ [(respond (consulted c)).val]) us := rfl

theorem unrelated_adds_no_gate (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : ¬ Reaches (consulted (fuse c u))) :
    grasp respond session c (u :: us) =
      grasp respond session
        (consulted (fuse c u) ++ [(session (consulted (fuse c u))).val]) us := by
  simp [grasp, h]

theorem withdraw_closes_unclosed (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hr : Reaches (consulted (fuse c u)))
    (h : isFilled (withdrawal (consulted (fuse c u))) = true) :
    grasp respond session c (u :: us) = .withdrawn (closed (consulted (fuse c u))) := by
  simp [grasp, hr, h]

theorem closure_verifies (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (consulted (fuse c u)))
    (hw : isFilled (withdrawal (consulted (fuse c u))) = false)
    (hc : isFilled (closure (consulted (fuse c u))) = true) :
    grasp respond session c (u :: us) = .verified ⟨closed (consulted (fuse c u))⟩ := by
  simp [grasp, hre, hw, hc]

theorem unclosed_presents_again (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (consulted (fuse c u)))
    (hw : isFilled (withdrawal (consulted (fuse c u))) = false)
    (hc : isFilled (closure (consulted (fuse c u))) = false) :
    grasp respond session c (u :: us) =
      grasp respond session
        (consulted (fuse c u) ++ [(respond (consulted (fuse c u))).val]) us := by
  simp [grasp, hre, hw, hc]

theorem each_step_continues_or_closes (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (o : Outcome P)
    (h : grasp respond session c (u :: us) = o) :
    (∃ c', grasp respond session c' us = o) ∨
    (isFilled (withdrawal (consulted (fuse c u))) = true ∧
      o = .withdrawn (closed (consulted (fuse c u)))) ∨
    (isFilled (closure (consulted (fuse c u))) = true ∧
      o = .verified ⟨closed (consulted (fuse c u))⟩) := by
  simp only [grasp] at h
  split at h
  · exact .inl ⟨_, h⟩
  · split at h
    · exact .inr (.inl ⟨by assumption, h.symm⟩)
    · split at h
      · exact .inr (.inr ⟨by assumption, h.symm⟩)
      · exact .inl ⟨_, h⟩

theorem verified_by_person_closure (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : VerifiedUnderstanding P)
    (h : grasp respond session c us = .verified r) :
    ∃ c₀, isFilled (closure c₀) = true ∧ r = ⟨closed c₀⟩ := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨hc, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨_, hc, rfl⟩

theorem withdrawn_by_person_withdrawal (respond session : Context P → Response P)
    (c : Context P) (us : List (Utterance P)) (r : Closed P)
    (h : grasp respond session c us = .withdrawn r) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀ := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨hw, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, hw, rfl⟩
    · cases h'

theorem closure_carries_record (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : VerifiedUnderstanding P)
    (h : grasp respond session c us = .verified r) :
    ∃ c₀, isFilled (closure c₀) = true ∧ r.closure.context = c₀ ∧
      r.closure.residual = residual c₀ ∧ r.closure.dissent = dissent c₀ := by
  obtain ⟨c₀, hc, rfl⟩ := verified_by_person_closure respond session c us r h
  exact ⟨c₀, hc, rfl, rfl, rfl⟩

theorem shown_by_person (c : Context P) :
    ∀ s ∈ shown c, s.src.src.val = .person ∧
      ShownSupported c (c[s.src.idx]'s.src.lt) s.aspect s.measure s.help :=
  fun s _ => ⟨s.byPerson, s.supported⟩

theorem residual_unshown (c : Context P) (a : Entry) (h : a ∈ residual c) :
    ∀ s ∈ shown c, s.aspect ≠ a := by
  intro s hs hsa
  simp only [residual, List.mem_filter, Bool.not_eq_eq_eq_not, Bool.not_true,
    List.any_eq_false, beq_iff_eq] at h
  exact h.2 s hs hsa

theorem unshown_in_residual (c : Context P) (a : Entry) (ha : a ∈ aspects c)
    (hn : ∀ s ∈ shown c, s.aspect ≠ a) : a ∈ residual c := by
  simp only [residual, List.mem_filter, Bool.not_eq_eq_eq_not, Bool.not_true,
    List.any_eq_false, beq_iff_eq]
  exact ⟨ha, hn⟩

end Katalepsis
