module

public import Contract.Katalepsis

/-! The theorems the /grasp contract guarantees, each stated and proved here; `Contract.Katalepsis`
    is the SKILL.md Lean block, generated by lean-contract.js. Every public theorem is a guarantee
    the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Katalepsis

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

theorem silence (respond session : Context P → Response P) (c : Context P) :
    grasp respond session c [] = .holding c := by
  simp [grasp]

theorem start_presents_first (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) :
    start respond session c us =
      grasp respond session (consulted c ++ [(respond (consulted c)).val]) us := rfl

theorem unrelated_adds_no_gate (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (h : ¬ Reaches (consulted (fuse c u))) :
    grasp respond session c (u :: us) =
      grasp respond session
        (consulted (fuse c u) ++ [(session (consulted (fuse c u))).val]) us := by
  simp [grasp, h]

theorem withdraw_closes_unclosed (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hr : Reaches (consulted (fuse c u)))
    (h : isFilled (withdrawal (consulted (fuse c u))) = true) :
    grasp respond session c (u :: us) = .withdrawn (closed (consulted (fuse c u))) := by
  simp [grasp, hr, h]

theorem closure_verifies (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (consulted (fuse c u)))
    (hw : isFilled (withdrawal (consulted (fuse c u))) = false)
    (hc : isFilled (closure (consulted (fuse c u))) = true) :
    grasp respond session c (u :: us) = .verified ⟨closed (consulted (fuse c u))⟩ := by
  simp [grasp, hre, hw, hc]

theorem unclosed_presents_again (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (hre : Reaches (consulted (fuse c u)))
    (hw : isFilled (withdrawal (consulted (fuse c u))) = false)
    (hc : isFilled (closure (consulted (fuse c u))) = false) :
    grasp respond session c (u :: us) =
      grasp respond session
        (consulted (fuse c u) ++ [(respond (consulted (fuse c u))).val]) us := by
  simp [grasp, hre, hw, hc]

theorem each_step_continues_or_closes (respond session : Context P → Response P) (c : Context P)
    (u : Utterance P) (us : List (Utterance P)) (o : Outcome P)
    (h : grasp respond session c (u :: us) = o) :
    (∃ c', grasp respond session c' us = o) ∨
    (isFilled (withdrawal (consulted (fuse c u))) = true ∧
      o = .withdrawn (closed (consulted (fuse c u)))) ∨
    (isFilled (closure (consulted (fuse c u))) = true ∧
      o = .verified ⟨closed (consulted (fuse c u))⟩) := by
  simp only [grasp] at h
  split at h
  · exact .inl ⟨_, h⟩
  · split at h
    · exact .inr (.inl ⟨by assumption, h.symm⟩)
    · split at h
      · exact .inr (.inr ⟨by assumption, h.symm⟩)
      · exact .inl ⟨_, h⟩

theorem verified_by_person_closure (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : VerifiedUnderstanding P)
    (h : grasp respond session c us = .verified r) :
    ∃ c₀, isFilled (closure c₀) = true ∧ r = ⟨closed c₀⟩ := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨hc, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨_, hc, rfl⟩

theorem withdrawn_by_person_withdrawal (respond session : Context P → Response P)
    (c : Context P) (us : List (Utterance P)) (r : Closed P)
    (h : grasp respond session c us = .withdrawn r) :
    ∃ c₀, isFilled (withdrawal c₀) = true ∧ r = closed c₀ := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨hw, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨_, hw, rfl⟩
    · cases h'

theorem verified_at_an_utterance (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : VerifiedUnderstanding P)
    (h : grasp respond session c us = .verified r) :
    ∃ (c₀ : Context P) (u : Utterance P), r.closure.context = consulted (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
    · cases h'
      exact ⟨c, u, rfl⟩

theorem withdrawn_at_an_utterance (respond session : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (r : Closed P)
    (h : grasp respond session c us = .withdrawn r) :
    ∃ (c₀ : Context P) (u : Utterance P), r.context = consulted (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [grasp] at h
  | cons u us ih =>
    rcases each_step_continues_or_closes respond session c u us _ h with
        ⟨c', h'⟩ | ⟨_, h'⟩ | ⟨_, h'⟩
    · exact ih c' h'
    · cases h'
      exact ⟨c, u, rfl⟩
    · cases h'

theorem shown_by_person (c : Context P) :
    ∀ x ∈ shown c, x.2.src.src.val = .person ∧
      ShownSupported c x.2.src x.1 x.2.measure x.2.help :=
  fun x _ => ⟨x.2.byPerson, x.2.supported⟩

theorem residual_is_unshown (c : Context P) (a : Entry) :
    a ∈ residual c ↔ a ∈ aspects c ∧ showing c a = none := by
  simp [residual, Option.isNone_iff_eq_none]

theorem scope_only_by_person {c : Context P} {s : Cite c}
    (ok : (scopeCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem closed_only_by_person {c : Context P} {s : Cite c}
    (ok : (closureCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem withdrawn_only_by_person {c : Context P} {s : Cite c}
    (ok : (withdrawalCoord (P := P)).admits s.src) : s.src.val = .person := ok

-- About the annotations TOOL GROUNDING declares: no operation is annotated `.transform` or
-- `.dispatch`. It reads the declaration, not what a run does.
theorem writes_and_dispatches_nothing (op : Op) :
    (grounding op).1 ≠ .transform ∧ (grounding op).1 ≠ .dispatch := by
  cases op <;> simp [grounding]

end Katalepsis
