module

public import Contract.Epharmoge

/-! Proofs of the theorems the /contextualize SKILL.md Lean block states; `Contract.Epharmoge` is
    that block, generated by lean-contract.js. -/

public section

open Ground

namespace Epharmoge

variable {P : Type}

theorem silence (respond : Context P → Response P) (c : Context P) :
    contextualize respond c [] = .holding c := by
  simp [contextualize]

theorem unclosed_holds_gate (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Closable (pass (fuse c u))) :
    contextualize respond c (u :: us) =
      contextualize respond (pass (fuse c u) ++ [(respond (pass (fuse c u))).val]) us := by
  simp [contextualize, h]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  let c₁ := c ++ (perform c).map (·.val)
  let c₂ := c₁ ++ (passRecord c₁).map (·.val)
  exact ⟨(perform c).map (·.val) ++ (passRecord c₁).map (·.val) ++ (persist c₂).map (·.val),
    by simp [pass, c₁, c₂]⟩

theorem pending_passes {c : Context P} {m : Mismatch} (h : m ∈ pending c) :
    status c m = .pass := by
  simp only [pending, List.mem_filter, Bool.and_eq_true, decide_eq_true_eq] at h
  exact h.2.1

theorem person_route_is_route (c : Context P) (m : Mismatch) (d : Deficit)
    (h : filledValue (attribution c m.id) = some (.route d)) : status c m = .route d := by
  simp [status, h]

theorem route_unjudged (c : Context P) (m : Mismatch) (r : DispositionRecord) (d : Deficit)
    (h : record c m = some r) (hd : r.disposition = .route d) : r.judgedBy = .unjudged := by
  unfold record at h
  split at h
  · unfold closedAtJudgment at h
    split at h
    · split at h
      · split at h
        · cases h; simp at hd
        · cases h; simp at hd
      · cases h; simp at hd
    · split at h
      · cases h; simp at hd
      · cases h
  · unfold closedAtRegistration at h
    split at h
    · cases h; rfl
    · cases h; rfl
    · cases h
    · split at h
      · cases h; rfl
      · cases h

theorem overruled_keeps (c : Context P) (m : Mismatch) (r : DispositionRecord)
    (h : record c m = some r) (hv : r.verdict = some .overruled) :
    r.disposition = .answered .keep := by
  unfold record at h
  split at h
  · unfold closedAtJudgment at h
    split at h
    · rename_i a _ _ _ _
      split at h
      · split at h
        · cases h; simp at hv; simp [a.wellFormed hv]
        · cases h; simp at hv; simp [a.wellFormed hv]
      · cases h; simp at hv; simp [a.wellFormed hv]
    · split at h
      · cases h; rfl
      · cases h
  · unfold closedAtRegistration at h
    split at h
    · cases h; simp at hv
    · cases h; simp at hv
    · cases h
    · split at h
      · cases h; simp at hv
      · cases h

theorem relay_close_keeps (c : Context P) (m : Mismatch) (r : DispositionRecord)
    (h : record c m = some r) (ha : r.assignedBy = .relay) : r.disposition = .answered .keep := by
  unfold record at h
  split at h
  · unfold closedAtJudgment at h
    split at h
    · split at h
      · split at h
        · cases h; simp at ha
        · cases h; simp at ha
      · cases h; simp at ha
    · split at h
      · cases h; rfl
      · cases h
  · unfold closedAtRegistration at h
    split at h
    · cases h; simp at ha
    · cases h; simp at ha
    · cases h
    · split at h
      · cases h; simp at ha
      · cases h

theorem confirmed_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (v : ApplicabilityVerdict P)
    (h : contextualize respond c us = .confirmed v) :
    ∃ (c₀ : Context P) (u : Utterance P), v.context = pass (fuse c₀ u) ∧ Accepted v.context := by
  induction us generalizing c with
  | nil => simp [contextualize] at h
  | cons u us ih =>
    simp only [contextualize] at h
    split at h
    · rename_i hc
      unfold close at h
      split at h
      · cases h
      · rename_i hw
        split at h
        · rename_i he
          cases h
          refine ⟨c, u, rfl, ?_⟩
          rcases hc with hc | hc | hc
          · simp [hw] at hc
          · exact hc.2
          · exact absurd he hc.1
        · split at h
          · cases h
          · cases h
    · exact ih _ h

theorem attributed_by_utterance {c : Context P} {i : MismatchId} {s : Cite c}
    (ok : (attributionCoord (P := P) i).admits s.kind) : s.kind = .utterance := ok

theorem answered_by_utterance {c : Context P} {i : MismatchId} {s : Cite c}
    (ok : (answerCoord (P := P) i).admits s.kind) : s.kind = .utterance := ok

theorem accepted_by_utterance {c : Context P} {s : Cite c}
    (ok : (zeroCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

end Epharmoge
