module

public import Contract.Epharmoge
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /contextualize SKILL.md Lean block states; `Contract.Epharmoge` is
    that block, generated by lean-contract.js. -/

public section

open Ground

namespace Epharmoge

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Certificate := ⟨⟨[], List.nodup_nil, by simp, ""⟩⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    contextualize respond c [] = .holding c := by
  simp [contextualize]

theorem unclosed_holds_gate (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Closable (pass (fuse c u))) :
    contextualize respond c (u :: us) =
      contextualize respond (pass (fuse c u) ++ [(respond (pass (fuse c u))).val]) us := by
  simp [contextualize, h]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  let c₁ := c ++ (perform c).map (·.val)
  let c₂ := c₁ ++ (passRecord c₁).map (·.val)
  exact ⟨(perform c).map (·.val) ++ (passRecord c₁).map (·.val) ++ (persist c₂).map (·.val),
    by simp [pass, c₁, c₂]⟩

theorem person_first (c : Context P) (m : Mismatch c) (r : Resolution)
    (h : filledValue (resolution c m) = some r) : standing c m = .resolved r := by
  simp [standing, h]

theorem resolved_by_person (c : Context P) (m : Mismatch c) (r : Resolution)
    (h : standing c m = .resolved r) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  unfold standing at h
  cases hr : resolution c m with
  | filled a src ok _ =>
    exact ⟨src, ok, src.ok.trans ok⟩
  | open_ _ =>
    simp only [hr, filledValue] at h
    split at h
    · cases h
    · split at h <;> cases h

theorem evidence_not_person {c : Context P} {m : Mismatch c} {s : Cite c}
    (ok : (evidenceCoord m).admits s.src) : s.src.val ≠ .person := ok

theorem closing_by_person {c : Context P} {s : Cite c}
    (ok : (closeCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem done_closed_by_person (c : Context P) (v : ApplicabilityVerdict P) (hc : Closable c)
    (h : close c = .done v) : NothingOpen c ∧ PersonClosed c := by
  unfold close at h
  by_cases hw : Withdrawn c
  · simp [hw] at h
  · simp only [hw, ↓reduceIte] at h
    rcases hc with hw' | hs | ⟨t, ht⟩ | hdone
    · exact absurd hw' hw
    · simp [hs] at h
    · simp [ht] at h
    · exact hdone

theorem against_not_assistant {c : Context P} (m : Mismatch c) :
    (c[m.against.idx]'m.against.lt).origin ≠ .assistant :=
  cited_not_assistant m.against

end Epharmoge
