module

public import Contract.Epharmoge
public import EpistemicProtocols.Ground.Theorems

/-! The theorems the /contextualize contract guarantees, each stated and proved here;
    `Contract.Epharmoge` is the SKILL.md Lean block, generated by lean-contract.js. Every public
    theorem is a guarantee the audit lists; a `private` theorem is a helper for one of them. -/

public section

open Ground

namespace Epharmoge

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩

/-- Silence settles nothing: with no utterance, the last outcome stands. -/
theorem silence (respond session : Context P → Response P) (c : Context P) (o : Outcome P) :
    contextualize respond session c o [] = o := by
  simp [contextualize]

/-- An utterance that does not bear on this run adds only the session's answer to the context,
    and the last outcome stands. -/
theorem other_work_passes_nothing (respond session : Context P → Response P) (c : Context P)
    (o : Outcome P) (u : Utterance P) (us : List (Utterance P)) (h : ¬ Reaches (fuse c u)) :
    contextualize respond session c o (u :: us) =
      contextualize respond session (fuse c u ++ [(session (fuse c u)).val]) o us := by
  simp [contextualize, h]

/-- An utterance that bears on the run gets the session's answer to what it asks outside the run
    first, then opens a pass, completed or not. -/
theorem reaching_passes_again (respond session : Context P → Response P) (c : Context P)
    (o : Outcome P) (u : Utterance P) (us : List (Utterance P)) (h : Reaches (fuse c u)) :
    contextualize respond session c o (u :: us) =
      contextualize respond session
        (settle respond (pass (fuse c u ++ [(session (fuse c u)).val]))).context
        (settle respond (pass (fuse c u ++ [(session (fuse c u)).val]))) us := by
  simp [contextualize, h]

/-- Completion needs nothing open. -/
theorem completed_nothing_open (respond : Context P → Response P) (c : Context P)
    (v : ApplicabilityVerdict P) (h : settle respond c = .completed v) : NothingOpen c := by
  unfold settle at h
  by_cases hc : NothingOpen c
  · exact hc
  · simp [hc] at h

/-- A settled standing never rests on a resolution that asks for a write: such a mismatch stays
    open until its write repairs it and takes it out of what is found. -/
theorem settled_asks_no_write (c : Context P) (m : Mismatch c) (r : Resolution) (how : How)
    (hs : standing c m = .resolved r how ∨ standing c m = .relayed r) : r.asksWrite = false := by
  unfold standing at hs
  cases hr : resolution c m with
  | filled a src ok sup =>
    obtain ⟨r₀, h₀⟩ := a
    simp only [hr, filledValue] at hs
    by_cases hw : r₀.asksWrite <;> simp [hw] at hs
    obtain ⟨rfl, -⟩ := hs
    simpa using hw
  | open_ _ =>
    simp only [hr, filledValue] at hs
    cases he : byEvidence c m with
    | filled a src ok sup =>
      cases a with
      | withdraw => simp [he] at hs
      | resolves r₀ =>
        simp only [he] at hs
        by_cases hw : r₀.asksWrite <;> simp [hw] at hs
        subst hs
        simpa using hw
    | open_ _ => simp [he] at hs

/-- The person's resolution comes first, whatever evidence read: one that asks no write stands
    resolved. -/
theorem person_first (c : Context P) (m : Mismatch c) (r : Resolution) (how : How)
    (h : filledValue (resolution c m) = some (r, how)) (hw : r.asksWrite = false) :
    standing c m = .resolved r how := by
  simp [standing, h, hw]

/-- A resolution on the person's record cites a turn the person sent. -/
theorem resolved_by_person (c : Context P) (m : Mismatch c) (r : Resolution) (how : How)
    (h : standing c m = .resolved r how) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  unfold standing at h
  cases hr : resolution c m with
  | filled a src ok _ =>
    exact ⟨src, ok, src.ok.trans ok⟩
  | open_ _ =>
    simp only [hr, filledValue] at h
    split at h <;> (try split at h) <;> cases h

/-- A relayed resolution cites evidence the person did not send. -/
theorem relayed_not_person (c : Context P) (m : Mismatch c) (r : Resolution)
    (h : standing c m = .relayed r) :
    ∃ s : Cite c, s.src.val ≠ .person ∧ (c[s.idx]'s.lt).origin ≠ .person := by
  unfold standing at h
  cases hr : resolution c m with
  | filled a src ok _ =>
    simp only [hr, filledValue] at h
    split at h <;> cases h
  | open_ _ =>
    simp only [hr, filledValue] at h
    cases he : byEvidence c m with
    | filled a src ok _ =>
      exact ⟨src, ok, by rw [src.ok]; exact ok⟩
    | open_ _ =>
      simp [he] at h

/-- Evidence never stands on the person's say-so. -/
theorem evidence_not_person {c : Context P} {m : Mismatch c} {s : Cite c}
    (ok : (evidenceCoord m).admits s.src) : s.src.val ≠ .person := ok

private theorem relayRounds_extends : ∀ (n : Nat) (c : Context P), ∃ t, relayRounds n c = c ++ t
  | 0, c => ⟨[], by simp [relayRounds]⟩
  | n + 1, c => by
    by_cases hs : Settling c
    · obtain ⟨t, ht⟩ := relayRounds_extends n (relayRound c)
      refine ⟨(perform c ++ (observe (c ++ perform c)).map (·.val)) ++ t, ?_⟩
      simp only [relayRounds, hs, ite_true, ht]
      simp [relayRound]
    · exact ⟨[], by simp [relayRounds, hs]⟩

/-- A pass only adds to the context. -/
theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  obtain ⟨t, ht⟩ := relayRounds_extends (rounds (c ++ (observe c).map (·.val)))
    (c ++ (observe c).map (·.val))
  exact ⟨(observe c).map (·.val) ++ t, by simp [pass, ht]⟩

theorem against_not_assistant {c : Context P} (m : Mismatch c) :
    (c[m.against.idx]'m.against.lt).origin ≠ .assistant :=
  cited_not_assistant m.against

end Epharmoge
