module

public import Contract.Epharmoge

/-! The theorems the /contextualize contract has. `Contract.Epharmoge` is the SKILL.md Lean block,
    generated by lean-contract.js; `Proofs.lean` proves each theorem stated here, and the
    lean-definition check re-derives every statement from the proved theorem of its name. The
    runtime surface carries only what the model reads, so the statements live here. -/

namespace Epharmoge

variable {P : Type}

/-!
Silence judges nothing and closes nothing.
theorem silence (respond : Context P → Response P) (c : Context P) :
    contextualize respond c [] = .holding c

While no closure fires, an utterance leads to the next gate and closes nothing.
theorem unclosed_holds_gate (respond : Context P → Response P) (c : Context P) (u : Utterance P)
    (us : List (Utterance P)) (h : ¬ Closable (pass (fuse c u))) :
    contextualize respond c (u :: us) =
      contextualize respond (pass (fuse c u) ++ [(respond (pass (fuse c u))).val]) us

A pass only adds to the context.
theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t

The person's resolution stands over anything evidence or the certificate read.
theorem person_first (c : Context P) (m : Mismatch c) (r : Resolution)
    (h : filledValue (resolution c m) = some r) : standing c m = .resolved r

A mismatch whose owner is unclear waits on the person until they resolve it; evidence does not
withdraw it first.
theorem unclear_waits (c : Context P) (m : Mismatch c) (hr : filledValue (resolution c m) = none)
    (hu : (certify c m).whose = .unclear) : standing c m = .open_

A resolution always rests on a turn the person sent.
theorem resolved_by_person (c : Context P) (m : Mismatch c) (r : Resolution)
    (h : standing c m = .resolved r) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person

Evidence never rests on the person's say-so.
theorem evidence_not_person {c : Context P} {m : Mismatch c} {s : Cite c}
    (ok : (evidenceCoord m).admits s.src) : s.src.val ≠ .person

Only the person closes.
theorem closing_by_person {c : Context P} {s : Cite c}
    (ok : (closeCoord (P := P)).admits s.src) : s.src.val = .person

A done run has nothing open, and the person closed it.
theorem done_closed_by_person (c : Context P) (v : ApplicabilityVerdict P) (hc : Closable c)
    (h : close c = .done v) : NothingOpen c ∧ PersonClosed c

A mismatch never stands against the assistant's own turn.
theorem against_not_assistant {c : Context P} (m : Mismatch c) :
    (c[m.against.idx]'m.against.lt).origin ≠ .assistant
-/

end Epharmoge
