module

public import Contract.Merismos
public import EpistemicProtocols.Ground.Proofs

/-! Proofs of the theorems the /apportion SKILL.md Lean block states; `Contract.Merismos` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Merismos

variable {P : Type}

/-! Every judgment the block declares as an `axiom` has an inhabited type; these witnesses carry no
    meaning and exist so that no judgment can assume what nothing inhabits. -/

instance {A : Type} {q : Coord P A} {c : Context P} : Nonempty (Occ q c) := ⟨.open_ none⟩
instance : Nonempty Derivation := ⟨⟨[], [], []⟩⟩

theorem silence (respond : Context P → Response P) (c : Context P) :
    apportion respond c [] = .holding c := by
  simp [apportion]

theorem pass_extends (c : Context P) : ∃ t, pass c = c ++ t := by
  let c₁ := c ++ (collect c).map (·.val)
  exact ⟨(collect c).map (·.val) ++ (passRecord c₁).map (·.val), by simp [pass, c₁]⟩

theorem apportioned_on_take (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (a : Apportioned P) (h : apportion respond c us = .apportioned a) :
    ∃ c₁ : Context P, filledValue (closing c₁) = some .take ∧ Closable c₁ ∧ a = close c₁ ∧
      Recorded a.navigation a.context := by
  induction us generalizing c with
  | nil => simp [apportion] at h
  | cons u us ih =>
    simp only [apportion] at h
    split at h
    · cases h
    · cases h
    · rename_i hk
      split at h
      · rename_i hc
        split at h
        · rename_i hr
          cases h
          exact ⟨_, hk, hc, rfl, hr⟩
        · exact ih _ h
      · exact ih _ h
    · exact ih _ h

theorem withdrawn_on_stop (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (h : apportion respond c us = .withdrawn c₁) :
    filledValue (closing c₁) = some .stop := by
  induction us generalizing c with
  | nil => simp [apportion] at h
  | cons u us ih =>
    simp only [apportion] at h
    split at h
    · rename_i hk
      cases h
      exact hk
    · cases h
    · split at h
      · split at h
        · cases h
        · exact ih _ h
      · exact ih _ h
    · exact ih _ h

theorem routed_on_route (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (t : String) (c₁ : Context P)
    (h : apportion respond c us = .routed t c₁) : filledValue (closing c₁) = some (.route t) := by
  induction us generalizing c with
  | nil => simp [apportion] at h
  | cons u us ih =>
    simp only [apportion] at h
    split at h
    · cases h
    · rename_i hk
      cases h
      exact hk
    · split at h
      · split at h
        · cases h
        · exact ih _ h
      · exact ih _ h
    · exact ih _ h

theorem closed_by_person (c : Context P) (k : Closing) (h : filledValue (closing c) = some k) :
    ∃ s : Cite c, s.src.val = .person ∧ (c[s.idx]'s.lt).origin = .person := by
  cases hc : closing c with
  | open_ _ => simp [hc, filledValue] at h
  | filled a src ok _ => exact ⟨src, ok, src.ok.trans ok⟩

theorem acceptance_by_person {c : Context P} {s : Cite c}
    (ok : (acceptanceCoord (P := P)).admits s.src) : s.src.val = .person := ok

theorem override_by_person {c : Context P} {u : PlanUnit} {s : Cite c}
    (ok : (overrideCoord (P := P) u).admits s.src) : s.src.val = .person := ok

theorem recommended_separates (c : Context P) (f : Focus) (i : {i : Nat // Separates c f i})
    (_ : recommend c f = some i) : Separates c f i.val := i.property

theorem residual_empty_iff_covered (c : Context P) :
    residual c = [] ↔ coverageComplete c = true := by
  simp [residual, coverageComplete, List.filter_eq_nil_iff, List.all_eq_true]

theorem closable_certifies (c : Context P) (h : Closable c) (u : PlanUnit) (hu : u ∈ units c) :
    (certificate (derivation c u)).terminates = true := by
  have hs := h.1
  simp only [Structural, status, Bool.and_eq_true] at hs
  obtain ⟨⟨⟨⟨⟨⟨⟨⟨_, _⟩, _⟩, _⟩, ht⟩, _⟩, _⟩, _⟩, _⟩ := hs
  simp only [terminationCovered, List.all_eq_true] at ht
  exact ht u hu

theorem reservation_not_hidden (d : Derivation) (s : Reservation) (hs : s ∈ d.reserved) :
    s ∈ (certificate d).reserved := hs

theorem closable_nonempty (c : Context P) (h : Closable c) : units c ≠ [] ∨ oos c ≠ [] := by
  have hs := h.1
  simp only [Structural, status, Bool.and_eq_true] at hs
  obtain ⟨_, hn⟩ := hs
  cases hu : units c with
  | nil => cases ho : oos c with
    | nil => simp [hu, ho] at hn
    | cons _ _ => exact Or.inr (by simp)
  | cons _ _ => exact Or.inl (by simp)

theorem unfit_needs_person (c : Context P) (h : Closable c) (u : PlanUnit) (hu : u ∈ units c)
    (hf : u.fit ≠ .fits) :
    ∃ (a : Override) (s : Cite c) (ok : (overrideCoord (P := P) u).admits s.src)
      (sup : OverrideSupported u c (c[s.idx]'s.lt) a), override c u = .filled a s ok sup := by
  have hs := h.1
  simp only [Structural, status, Bool.and_eq_true] at hs
  obtain ⟨⟨⟨⟨⟨⟨⟨⟨_, _⟩, hfit⟩, _⟩, _⟩, _⟩, _⟩, _⟩, _⟩ := hs
  simp only [fitSettled, List.all_eq_true] at hfit
  have hu' := hfit u hu
  cases ho : override c u with
  | open_ _ => simp [ho, isFilled, hf] at hu'
  | filled a src ok sup => exact ⟨a, src, ok, sup, rfl⟩

theorem emitted_refs_nodup (c : Context P) : ((emit c).units.map (·.ref)).Nodup := by
  have key : ∀ (f : Nat × PlanUnit → UnitEntry), (∀ x, (f x).ref = x.1) →
      ∀ l : List (Nat × PlanUnit), (l.map f).map (·.ref) = l.map Prod.fst := by
    intro f hf l
    induction l with
    | nil => rfl
    | cons x l ih => simp [ih, hf]
  have h : ((emit c).units.map (·.ref)) = List.range (units c).length := by
    simp only [emit]
    rw [key _ (fun x => by obtain ⟨i, u⟩ := x; rfl)]
    exact List.map_fst_zip (by simp)
  rw [h]
  exact List.nodup_range

theorem acceptance_bound_to_units (c : Context P) (p : PlanCondition) (hp : p ∈ planOf c)
    (hs : p.scope = .wholeGoalAcceptance) :
    p.dischargeableWhen = planTerminal (units c).length := by
  simp only [planOf, List.mem_map] at hp
  obtain ⟨q, _, rfl⟩ := hp
  by_cases hq : q.scope = .wholeGoalAcceptance
  · simp [bindPlan, hq]
  · simp [bindPlan, hq] at hs

theorem waiver_reservation_exclusive (c : Context P) :
    ¬ ((envelope c).waived = true ∧ (envelope c).reserved.any (·.subject.isAcceptance) = true) := by
  simp only [envelope]
  cases filledValue (acceptance c) with
  | none => simp
  | some a =>
    cases a <;> simp [List.any_flatMap, List.any_map, ReservedSubject.isAcceptance]

theorem plan_reads_back (e : Emission) (ds : List String) (pv : List Provenance) :
    (package e ds pv).units = e.units ∧ (package e ds pv).planConditions = e.planConditions ∧
      (package e ds pv).reserved = e.envelope.reserved ∧
      (package e ds pv).waived = e.envelope.waived :=
  ⟨rfl, rfl, rfl, rfl⟩

theorem navigation_locates_carrier (c : Context P) :
    (navigation c).canonicalLocator = ⟨carrierRecord c, sessionId c⟩ := rfl

end Merismos
