module

public import Contract.Merismos

/-! Proofs of the theorems the /apportion SKILL.md Lean block states; `Contract.Merismos` is that
    block, generated by lean-contract.js. -/

public section

open Ground

namespace Merismos

variable {P : Type}

theorem silence (respond : Context P → Response P) (c : Context P) :
    apportion respond c [] = .holding c := by
  simp [apportion]

theorem apportioned_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (a : Apportioned P) (h : apportion respond c us = .apportioned a) :
    ∃ (c₀ : Context P) (u : Utterance P), verdict (fuse c₀ u) = .confirm ∧
      closable (fuse c₀ u) = true ∧ a = close (fuse c₀ u) := by
  induction us generalizing c with
  | nil => simp [apportion] at h
  | cons u us ih =>
    simp only [apportion] at h
    split at h
    · cases h
    · rename_i hv
      split at h
      · rename_i hc
        cases h
        exact ⟨c, u, hv, hc, rfl⟩
      · exact ih _ h
    · split at h
      · cases h
      · exact ih _ h

theorem rerouted_by_person (respond : Context P → Response P) (c : Context P)
    (us : List (Utterance P)) (c₁ : Context P) (h : apportion respond c us = .rerouted c₁) :
    ∃ (c₀ : Context P) (u : Utterance P), c₁ = fuse c₀ u ∧ verdict c₁ = .routeBound := by
  induction us generalizing c with
  | nil => simp [apportion] at h
  | cons u us ih =>
    simp only [apportion] at h
    split at h
    · rename_i hv
      cases h
      exact ⟨c, u, rfl, hv⟩
    · split at h
      · cases h
      · exact ih _ h
    · split at h
      · cases h
      · exact ih _ h

theorem acceptance_by_utterance {c : Context P} {s : Cite c}
    (ok : (acceptanceCoord (P := P)).admits s.kind) : s.kind = .utterance := ok

theorem unfit_offers_no_accept (f : SpanFit) (b : Bool) (h : f ≠ .fits) :
    UnitForm.acceptUnit ∉ unitOptions f b := by
  cases f <;> cases b <;> simp_all [unitOptions]

theorem fit_offers_no_override (b : Bool) : UnitForm.overrideFit ∉ unitOptions .fits b := by
  cases b <;> simp [unitOptions]

theorem heuristic_sends_whole_draft (c : Context P) (y x : ProposedUnit) (hy : y ∈ draft c)
    (hh : y.seam.isHeuristic = true) : relays c x = false := by
  have : (draft c).any (fun y => y.seam.isHeuristic) = true := List.any_eq_true.mpr ⟨y, hy, hh⟩
  simp [relays, this]

theorem residual_empty_iff_covered (c : Context P) :
    residual c = [] ↔ coverageComplete c = true := by
  simp [residual, coverageComplete, List.filter_eq_nil_iff, List.all_eq_true]

theorem resolve_total (u : PlanUnit) (d : Derivation) (h : hasCompletion u d = true) :
    (resolveUnit u d.accept).isSome = true := by
  unfold resolveUnit
  split
  · rfl
  · rename_i hk
    split
    · rfl
    · rename_i hacc
      split
      · rfl
      · rename_i hres
        exfalso
        simp only [Derivation.accept] at hk hres hacc
        simp only [hasCompletion, Bool.or_eq_true] at h
        rcases h with (h | h) | h
        · exact hk h
        · simp only [acceptedCompletion, List.map_eq_nil_iff, List.filter_eq_nil_iff,
            List.mem_map] at hacc
          obtain ⟨r, hr, hr'⟩ := List.any_eq_true.mp h
          have := hacc _ ⟨r, hr, rfl⟩
          simp_all
        · simp only [reservedCompletion, List.map_eq_nil_iff, List.filter_eq_nil_iff] at hres
          obtain ⟨s, hs, hs'⟩ := List.any_eq_true.mp h
          exact hres s hs hs'

theorem every_unit_certified (c : Context P) (h : closable c = true) (u : PlanUnit)
    (hu : u ∈ units c) : (resolveUnit u (derivation c u).accept).isSome = true := by
  apply resolve_total
  simp only [closable, status, Bool.and_eq_true] at h
  have ht := h.1.1.1.1.2
  simp only [terminationCovered, List.all_eq_true] at ht
  exact ht u hu

theorem emitted_units_join (c : Context P) (e : UnitEntry) (he : e ∈ (emit c).units) :
    ∃ u ∈ units c, ∃ r, resolveUnit u (derivation c u).accept = some r ∧ e = entry u r := by
  simp only [emit, List.mem_filterMap, Option.map_eq_some_iff] at he
  obtain ⟨u, hu, r, hr, rfl⟩ := he
  exact ⟨u, hu, r, hr, rfl⟩

theorem acceptance_bound_to_units (c : Context P) (p : PlanCondition) (hp : p ∈ planOf c)
    (hs : p.scope = .wholeGoalAcceptance) :
    p.dischargeableWhen.predicate = .planTerminal (units c).length := by
  simp only [planOf, List.mem_map] at hp
  obtain ⟨q, _, rfl⟩ := hp
  unfold bindPlan at hs ⊢
  split
  · rfl
  · rename_i hq
    simp_all

theorem waiver_reservation_exclusive (c : Context P) :
    ¬ ((envelope c).unboundedApproved = true ∧
      (envelope c).reserved.any (·.subject.isAcceptance) = true) := by
  intro ⟨hu, hr⟩
  simp only [envelope] at hu hr
  cases ha : filledValue (acceptance c) with
  | none => simp [ha] at hu
  | some a =>
    cases a <;> simp_all [Acceptance.isUnbounded, Acceptance.isReserved,
      List.any_flatMap, List.any_map, ReservedSubject.isAcceptance, Function.comp_def]

theorem plan_reads_back (e : Emission) (ds : List String) :
    (package e ds).units = e.units ∧ (package e ds).planConditions = e.planConditions ∧
      (package e ds).reserved = e.envelope.reserved ∧
      (package e ds).unboundedApproved = e.envelope.unboundedApproved :=
  ⟨rfl, rfl, rfl, rfl⟩

theorem navigation_locates_carrier (c : Context P) :
    (navigation c).canonicalLocator = ⟨carrierRecord c, sessionId c⟩ := rfl

end Merismos
